res_items_cultures=[{'name':'种植术','progalias':'FOODCBUILD','bigpic':120001,'uptip':'粮食产量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ACC_FOOD,'val':'LV*20'}],'maxlevel':20,'id':120001,'desc':'增加粮食产量{1.val}%'}
,{'name':'伐木术','progalias':'WOODCBUILD','bigpic':120002,'uptip':'木材产量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ACC_WOOD,'val':'LV*20'}],'maxlevel':20,'id':120002,'desc':'增加木材产量{1.val}%'}
,{'name':'挖掘术','progalias':'STONECBUILD','bigpic':120003,'uptip':'石料产量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ACC_STONE,'val':'LV*20'}],'maxlevel':20,'id':120003,'desc':'增加石料产量{1.val}%'}
,{'name':'冶炼术','progalias':'IRONCBUILD','bigpic':120004,'uptip':'生铁产量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ACC_IRON,'val':'LV*20'}],'maxlevel':20,'id':120004,'desc':'增加生铁产量{1.val}%'}
,{'name':'建筑术','progalias':'BUILDCBUILD','bigpic':120005,'uptip':'建造速度增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ACCELERATE,'val':'LV*100'}],'maxlevel':20,'id':120005,'desc':'增加建造速度{1.val}%'}
,{'name':'刀兵训练','progalias':'DAOBINGCBUILD','bigpic':120006,'uptip':'可训练更高阶刀兵','effects':[{'u':VAL_UNIT.VAL,'id':RES_EFF.ADD_SOLDIERLEVEL,'val':'LV'}],'maxlevel':10,'id':120006,'desc':'可训练{1.val}阶刀兵'}
,{'name':'刀兵力量','progalias':'','bigpic':120007,'uptip':'刀兵力量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_DB_STR,'val':'LV*20'}],'maxlevel':20,'id':120007,'desc':'刀兵力量增加{1.val}%'}
,{'name':'刀兵根骨','progalias':'','bigpic':120008,'uptip':'刀兵骨根增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_DB_PHY,'val':'LV*20'}],'maxlevel':20,'id':120008,'desc':'刀兵骨根增加{1.val}%'}
,{'name':'刀兵身法','progalias':'','bigpic':120009,'uptip':'刀兵身法增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_DB_AGILE,'val':'LV*20'}],'maxlevel':20,'id':120009,'desc':'刀兵身法增加{1.val}%'}
,{'name':'刀兵重铠','progalias':'','bigpic':120010,'uptip':'刀兵重铠','effects':[{'u':0,'id':0,'val':''}],'maxlevel':20,'id':120010,'desc':'刀兵重铠'}
,{'name':'戟兵训练','progalias':'JIBINGCBUILD','bigpic':120011,'uptip':'可训练更高阶戟兵','effects':[{'u':VAL_UNIT.VAL,'id':RES_EFF.ADD_SOLDIERLEVEL,'val':'LV'}],'maxlevel':10,'id':120011,'desc':'可训练{1.val}阶戟兵'}
,{'name':'戟兵力量','progalias':'','bigpic':120012,'uptip':'戟兵力量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_JB_STR,'val':'LV*20'}],'maxlevel':20,'id':120012,'desc':'戟兵力量增加{1.val}%'}
,{'name':'戟兵根骨','progalias':'','bigpic':120013,'uptip':'戟兵骨根增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_JB_PHY,'val':'LV*20'}],'maxlevel':20,'id':120013,'desc':'戟兵骨根增加{1.val}%'}
,{'name':'戟兵身法','progalias':'','bigpic':120014,'uptip':'戟兵身法增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_JB_AGILE,'val':'LV*20'}],'maxlevel':20,'id':120014,'desc':'戟兵身法增加{1.val}%'}
,{'name':'戟兵突刺','progalias':'','bigpic':120015,'uptip':'戟兵突刺','effects':[{'u':0,'id':0,'val':''}],'maxlevel':20,'id':120015,'desc':'戟兵突刺'}
,{'name':'弓兵训练','progalias':'','bigpic':120016,'uptip':'可训练更高阶弓兵','effects':[{'u':VAL_UNIT.VAL,'id':RES_EFF.ADD_SOLDIERLEVEL,'val':'LV'}],'maxlevel':10,'id':120016,'desc':'可训练{1.val}阶弓兵'}
,{'name':'弓兵力量','progalias':'','bigpic':120017,'uptip':'弓兵力量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_GB_STR,'val':'LV*20'}],'maxlevel':20,'id':120017,'desc':'弓兵力量增加{1.val}%'}
,{'name':'弓兵根骨','progalias':'','bigpic':120018,'uptip':'弓兵骨根增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_GB_PHY,'val':'LV*20'}],'maxlevel':20,'id':120018,'desc':'弓兵骨根增加{1.val}%'}
,{'name':'弓兵身法','progalias':'','bigpic':120019,'uptip':'弓兵身法增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_GB_AGILE,'val':'LV*20'}],'maxlevel':20,'id':120019,'desc':'弓兵身法增加{1.val}%'}
,{'name':'弓兵剑雨','progalias':'','bigpic':120020,'uptip':'弓兵剑雨','effects':[{'u':0,'id':0,'val':''}],'maxlevel':20,'id':120020,'desc':'弓兵剑雨'}
,{'name':'骑兵训练','progalias':'','bigpic':120021,'uptip':'可训练更高阶骑兵','effects':[{'u':VAL_UNIT.VAL,'id':RES_EFF.ADD_SOLDIERLEVEL,'val':'LV'}],'maxlevel':10,'id':120021,'desc':'可训练{1.val}阶骑兵'}
,{'name':'骑兵力量','progalias':'','bigpic':120022,'uptip':'骑兵力量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_QB_STR,'val':'LV*20'}],'maxlevel':20,'id':120022,'desc':'骑兵力量增加{1.val}%'}
,{'name':'骑兵根骨','progalias':'','bigpic':120023,'uptip':'骑兵骨根增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_QB_PHY,'val':'LV*20'}],'maxlevel':20,'id':120023,'desc':'骑兵骨根增加{1.val}%'}
,{'name':'骑兵身法','progalias':'','bigpic':120024,'uptip':'骑兵身法增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_QB_AGILE,'val':'LV*20'}],'maxlevel':20,'id':120024,'desc':'骑兵身法增加{1.val}%'}
,{'name':'骑兵挥砍','progalias':'','bigpic':120025,'uptip':'骑兵挥砍','effects':[{'u':0,'id':0,'val':''}],'maxlevel':20,'id':120025,'desc':'骑兵挥砍'}
,{'name':'器械训练','progalias':'','bigpic':120026,'uptip':'可训练更高阶器械','effects':[{'u':VAL_UNIT.VAL,'id':RES_EFF.ADD_SOLDIERLEVEL,'val':'LV'}],'maxlevel':10,'id':120026,'desc':'可训练{1.val}阶器械'}
,{'name':'器械力量','progalias':'','bigpic':120027,'uptip':'器械力量增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_QX_STR,'val':'LV*20'}],'maxlevel':20,'id':120027,'desc':'器械力量增加{1.val}%'}
,{'name':'器械根骨','progalias':'','bigpic':120028,'uptip':'器械骨根增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_QX_PHY,'val':'LV*20'}],'maxlevel':20,'id':120028,'desc':'器械骨根增加{1.val}%'}
,{'name':'器械身法','progalias':'','bigpic':120029,'uptip':'器械身法增加','effects':[{'u':VAL_UNIT.PER,'id':RES_EFF.ADD_QX_AGILE,'val':'LV*20'}],'maxlevel':20,'id':120029,'desc':'器械身法增加{1.val}%'}
,{'name':'骑兵蓄力','progalias':'','bigpic':120030,'uptip':'骑兵蓄力','effects':[{'u':0,'id':0,'val':''}],'maxlevel':20,'id':120030,'desc':'骑兵蓄力'}
,{'name':'君主武力','progalias':'','bigpic':120031,'uptip':'君主武力增加','effects':[{'u':VAL_UNIT.VAL,'id':RES_EFF.ADD_ROLE_FOR,'val':'LV*2'}],'maxlevel':50,'id':120031,'desc':'增加君主武力{1.val}点'}
,{'name':'君主内政','progalias':'','bigpic':120032,'uptip':'君主内政增加','effects':[{'u':VAL_UNIT.VAL,'id':RES_EFF.ADD_ROLE_IN,'val':'LV*2'}],'maxlevel':50,'id':120032,'desc':'增加君主内政{1.val}点'}
,{'name':'君主智谋','progalias':'','bigpic':120033,'uptip':'君主智谋增加','effects':[{'u':VAL_UNIT.VAL,'id':RES_EFF.ADD_ROLE_BR,'val':'LV*2'}],'maxlevel':50,'id':120033,'desc':'增加君主智谋{1.val}点'}
];


