/******************************************************************************
type == 0
	//无子节点
type == 1
	//0  1  2
type == 2
	//0
	//1
	//2
type == 3
	//0  1  2
	//3  4  5
	//6  7  8
	
  Copyright (C)  All rights reserved.
******************************************************************************/
uiback={
	mb:{
		btn1:{
			type:0,
			cls:{
				normal:['mb-button1-n'],
				press:['mb-button1-p'],
				hot:['mb-button1-n'],
				disable:['mb-button1-d']
			}
		}
		,btn2:{
			type:0,
			cls:{
				normal:['mb-button2-n'],
				press:['mb-button2-p'],
				hot:['mb-button2-n'],
				disable:['mb-button2-d']
			}
		}
		,btn3:{
			type:0,
			cls:{
				normal:['mb-button3-n'],
				press:['mb-button3-p'],
				hot:['mb-button3-n'],
				disable:['mb-button3-d']
			}
		}
		,btn4:{
			type:0,
			cls:{
				normal:['mb-button4-n'],
				press:['mb-button4-p'],
				hot:['mb-button4-h'],
				disable:['mb-button4-d']
			}
		}
		,btn5:{
			type:0,
			cls:{
				normal:['mb-button5-n'],
				press:['mb-button5-p'],
				hot:['mb-button5-h'],
				disable:['mb-button5-d']
			}
		}
		,btn6:{
			type:0,
			cls:{
				normal:['mb-button6-n'],
				press:['mb-button6-p'],
				hot:['mb-button6-h'],
				disable:['mb-button6-d']
			}
		}
		,btn7:{
			type:0,
			cls:{
				normal:['mb-button7-n'],
				press:['mb-button7-p'],
				hot:['mb-button7-h'],
				disable:['mb-button7-d']
			}
		}
		,btn8_expand:{
			type:0,
			cls:{
				normal:['mb-button8-expand-n'],
				press:['mb-button8-expand-p'],
				hot:['mb-button8-expand-h'],
				disable:['mb-button8-expand-d']
			}
		}
		,btn8_collapse:{
			type:0,
			cls:{
				normal:['mb-button8-collapse-n'],
				press:['mb-button8-collapse-p'],
				hot:['mb-button8-collapse-h'],
				disable:['mb-button8-collapse-d']
			}
		}
		,btn9_sound:{
			type:0,
			cls:{
				normal:['mb-smbtn-sound-n'],
				press:['mb-smbtn-sound-p'],
				hot:['mb-smbtn-sound-h'],
				blinking:['mb-smbtn-sound-h'],
				disable:['mb-smbtn-sound-n']
		   }
		}
		,btn10_suggest:{type:0,
		   cls:{
			normal:['mb-suggest_btn_n'],
			press:['mb-suggest_btn_p'],
			hot:['mb-suggest_btn_h'],
			disable:['mb-suggest_btn_n']
		   }
		}
		,btn10_suggest_new:{type:0,
		   cls:{
			normal:['mb-suggest_btn_n_new'],
			press:['mb-suggest_btn_p'],
			hot:['mb-suggest_btn_h'],
			disable:['mb-suggest_btn_n']
		   }
		}
		,btn11_vipbtn:{type:0,
		   cls:{
			normal:['mb-vip_btn_n'],
			press:['mb-vip_btn_p'],
			hot:['mb-vip_btn_h'],
			disable:['mb-vip_btn_n']
		   }
		}
		,btn12_helpspirit:{type:0,
		   cls:{
			normal:['mb-ui-spirit-min-n'],
			press:['mb-ui-spirit-min-p'],
			hot:['mb-ui-spirit-min-h'],
			disable:['mb-ui-spirit-min-n']
		   }
		}
		,closebtn1:{
			type:0,
			cls:{
				normal:['mb-ui-closebtn1-n'],
				press:['mb-ui-closebtn1-p'],
				hot:['mb-ui-closebtn1-h'],
				disable:['mb-ui-closebtn1-n']
			}
		}
		,facebtn:{
			type:0,
			cls:{
				normal:['mb-facebutton-n'],
				press:['mb-facebutton-p'],
				hot:['mb-facebutton-h'],
				disable:['mb-facebutton-d']
			}
		}
		,actdatebtn:{
			type:0,
			newFlag:{pos:{x:35, y:0},cls:'mb-ui-trackbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:-1, y:-1}, hot:{x:-1, y:-1}}},
			cls:{
				normal:['mb-ui-trackbtn-actdate-n'],
				press:['mb-ui-trackbtn-actdate-p'],
				hot:['mb-ui-trackbtn-actdate-h'],
				disable:['mb-ui-trackbtn-actdate-n']
		   }				
		}
		,autobuildbtn:{
			type:0,
			newFlag:{pos:{x:35, y:0},cls:'mb-ui-trackbtn-reddot', pos:{x:20, y:2}, offsets:{normal:{x:0, y:0}, press:{x:-1, y:-1}, hot:{x:-1, y:-1}}},
			cls:{
				normal:['mb-ui-trackbtn-autobuild-n'],
				press:['mb-ui-trackbtn-autobuild-p'],
				hot:['mb-ui-trackbtn-autobuild-h'],
				disable:['mb-ui-trackbtn-autobuild-n']
		   }				
		}
		,buildingbtn:{
			type:0,
			cls:{
				normal:['mb-ui-trackbtn-building-n'],
				press:['mb-ui-trackbtn-building-p'],
				hot:['mb-ui-trackbtn-building-h'],
				disable:['mb-ui-trackbtn-building-n']
		   }				
		}		
		,commdlg:{type:3,cls:['mb-ui-commdlg-1','mb-ui-commdlg-2','mb-ui-commdlg-3',
			'mb-ui-commdlg-4','mb-ui-commdlg-5','mb-ui-commdlg-6',
			'mb-ui-commdlg-7','mb-ui-commdlg-8','mb-ui-commdlg-9'],
			nbtn_cls:['mb-ui-commdlg-1','mb-ui-commdlg-2','mb-ui-commdlg-3',
			'mb-ui-commdlg-4','mb-ui-commdlg-5','mb-ui-commdlg-6',
			'mb-ui-commdlg-7n','mb-ui-commdlg-8n','mb-ui-commdlg-9n'],
			dragTitleH:58,
			canDrag:true
		}
	}	
	,dlg:{
		comm:{type:3,cls:['ui-commdlg-1','ui-commdlg-2','ui-commdlg-3',
			'ui-commdlg-4','ui-commdlg-5','ui-commdlg-6',
			'ui-commdlg-7','ui-commdlg-8','ui-commdlg-9'],
			nbtn_cls:['ui-commdlg-1','ui-commdlg-2','ui-commdlg-3',
			'ui-commdlg-4','ui-commdlg-5','ui-commdlg-6',
			'ui-commdlg-7n','ui-commdlg-8n','ui-commdlg-9n'],
			dragTitleH:58,
			canDrag:true
			}
		,chatpanel:{type:3,cls:['ui-chatpanel-1','ui-chatpanel-2','ui-chatpanel-3',
			'ui-chatpanel-4','ui-chatpanel-5','ui-chatpanel-6',
			'ui-chatpanel-7','ui-chatpanel-8','ui-chatpanel-9'],
			commclass:{dlg:'ui-minidlg'}}
		,npc:{type:3,cls:['ui-dlg2-1','ui-dlg2-2','ui-dlg2-3',
			'ui-dlg2-4','ui-dlg2-5','ui-dlg2-6',
			'ui-dlg2-7','ui-dlg2-8','ui-dlg2-9']}
		,minihelp:{type:3,cls:['ui-dlg4-1','ui-dlg4-2','ui-dlg4-3',
			'ui-dlg4-4','ui-dlg4-5','ui-dlg4-6',
			'ui-dlg4-7','ui-dlg4-8','ui-dlg4-9'],
			commclass:{dlg:'ui-minidlg'}}
		,minihelp:{type:3,cls:['ui-dlg4-1','ui-dlg4-2','ui-dlg4-3',
			'ui-dlg4-4','ui-dlg4-5','ui-dlg4-6',
			'ui-dlg4-7','ui-dlg4-8','ui-dlg4-9'],
			commclass:{dlg:'ui-minidlg'}}
		
		,noborder:{type:-1,commclass:{dlg:'ui-noborder_mdlg',mdlg:'ui-noborder_mdlg'}}
		,noborder2:{type:-1,commclass:{dlg:'ui-noborder_mdlg2',mdlg:'ui-noborder_mdlg2'}}
		,helpspirit:{type:0,cls:['ui-dlg-spirit'],
			commclass:{dlg:'ui-spiritdlg'}}
		,helptask:{type:3,cls:['ui-dlg4-1','ui-dlg4-2','ui-dlg4-3',
			'ui-dlg4-4','ui-dlg4-5','ui-dlg4-6',
			'ui-dlg4-7','ui-dlg4-8','ui-dlg4-9'],
			commclass:{dlg:'ui-helptask'}}
		,friendmain:{type:3,cls:['ui-dlg4-1','ui-dlg4-2','ui-dlg4-3',
			'ui-dlg4-4','ui-dlg4-5','ui-dlg4-6',
			'ui-dlg4-7','ui-dlg4-8','ui-dlg4-9'],
			commclass:{dlg:'ui-frienddlg'}}
		,teampanel:{type:-1,commclass:{dlg:'ui-teampanel'}}
		,helpspirit:{type:3
			,cls:['ui-dlg5-1','ui-dlg5-2','ui-dlg5-3',
			'ui-dlg5-4','ui-dlg5-5','ui-dlg5-6',
			'ui-dlg5-7','ui-dlg5-8','ui-dlg5-9']
			,commclass:{dlg:'ui-noborder_mdlg',mdlg:'ui-noborder_mdlg'}}
	},
	progress:{
		comm:{type:1,
			cls:['ui-prog-1', 'ui-prog-2', 'ui-prog-3'],
			backcls:'ui-prog-back',
			barcls:'ui-prog-bar',
			bar:{l:5,t:1,r:5,b:1}
		}
		,prog1:{type:1,
			cls:['ui-prog1-1', 'ui-prog1-2', 'ui-prog1-3'],
			backcls:'ui-prog1-back',
			barcls:'ui-prog1-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,smallhpprog:{type:1,
			cls:['ui-prog1-1', 'ui-prog1-2', 'ui-prog1-3'],
			backcls:'ui-prog1-back',
			barcls:'ui-shpprog-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,smallmpprog:{type:1,
			cls:['ui-prog1-1', 'ui-prog1-2', 'ui-prog1-3'],
			backcls:'ui-prog1-back',
			barcls:'ui-smpprog-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,buildvarprog:{type:1,
			cls:['ui-bprog-1', 'ui-bprog-2', 'ui-bprog-3'],
			backcls:'ui-bprog-back',
			barcls:'ui-bprogbar-bar',
			secbarcls:'ui-secbprogbar-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,smallmstrprog:{type:1,
			cls:['ui-prog1-1', 'ui-prog1-2', 'ui-prog1-3'],
			backcls:'ui-prog1-back',
			barcls:'ui-smstrprog-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,expprog:{type:1,
			cls:['ui-expprog-1', 'ui-expprog-2', 'ui-expprog-3'],
			backcls:'ui-expprog-back',
			barcls:'ui-expprog-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,hpprog:{type:1,
			cls:['ui-hpprog-1', 'ui-hpprog-2', 'ui-hpprog-3'],
			backcls:'ui-hpprog-back',
			barcls:'ui-hpprog-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,mpprog:{type:1,
			cls:['ui-mpprog-1', 'ui-mpprog-2', 'ui-mpprog-3'],
			backcls:'ui-mpprog-back',
			barcls:'ui-mpprog-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,anprog:{type:1,
			cls:['ui-anprog-1', 'ui-anprog-2', 'ui-anprog-3'],
			backcls:'ui-anprog-back',
			barcls:'ui-anprog-bar',
			bar:{l:1,t:1,r:1,b:1}
		}
		,mainroleexpprog:{type:0,
			cls:['ui-mainroleexpprog-front'],
			backcls:'ui-mainroleexpprog-back',
			barcls:'ui-mainroleexpprog-bar',
			bar:{l:0,t:0,r:0,b:0}
		}
		,lawlightprog:{type:0,
			cls:['ui-lawlightprog-front'],
			backcls:'ui-lawlightprog-back',
			barcls:'ui-lawlightprog-bar',
			bar:{l:5,t:0,r:5,b:0}
		}
		,actvalprog:{type:0,
			cls:['ui-actvalprog-front'],
			backcls:'ui-actvalprog-back',
			barcls:'ui-actvalprog-bar',
			bar:{l:0,t:0,r:0,b:0}
		}
		,vslefthpprog:{type:0,
			cls:['ui-vslefthpprog-front'],
			backcls:'ui-vslefthpprog-back',
			barcls:'ui-vslefthpprog-bar',
			bar:{l:66,t:0,r:0,b:0}
		}
		,vsrighthpprog:{type:0,
			cls:['ui-vsrighthpprog-front'],
			backcls:'ui-vsrighthpprog-back',
			barcls:'ui-vsrighthpprog-bar',
			bar:{l:0,t:0,r:66,b:0}
		}
	},
	panel:{
		panel1:{type:3,cls:['ui-panel1-1','ui-panel1-2','ui-panel1-3',
			'ui-panel1-4','ui-panel1-5','ui-panel1-6',
			'ui-panel1-7','ui-panel1-8','ui-panel1-9']}
	},
	tooltip:{
		tip:{type:3,cls:['ui-tip-1','ui-tip-2','ui-tip-3',
			'ui-tip-4','ui-tip-5','ui-tip-6',
			'ui-tip-7','ui-tip-8','ui-tip-9']}
	},
	scrollslider:{type:2,
			cls:['ui-scrollslider-1', 'ui-scrollslider-2', 'ui-scrollslider-3']
			,decorateCls:'ui-scrollslider-decorate'
	},
	btn:{
		comm:{type:1,
			   newFlag:{cls:'commbtn-reddot'},
			   cls:{
				normal:['ui-combtn-1-n', 'ui-combtn-2-n', 'ui-combtn-3-n'],
				press:['ui-combtn-1-p', 'ui-combtn-2-p', 'ui-combtn-3-p'],
				hot:['ui-combtn-1-h', 'ui-combtn-2-h', 'ui-combtn-3-h'],
				disable:['ui-combtn-1-d', 'ui-combtn-2-d', 'ui-combtn-3-d']
			   }
			},
		worldboss:{
				fight:{
					type:0,
					cls:{
					normal:['worldboss_fight_btn_n'],
					press:['worldboss_fight_btn_p'],
					hot:['worldboss_fight_btn_h'],
					disable:['worldboss_fight_btn_d']
					}
				},
				guwu:{
					type:0,
					cls:{
					normal:['worldboss_guwu_btn_n'],
					press:['worldboss_guwu_btn_p'],
					hot:['worldboss_guwu_btn_h'],
					disable:['worldboss_guwu_btn_d']
					}
				},
				guwus:{
					type:0,
					cls:{
					normal:['worldboss_guwus_btn_n'],
					press:['worldboss_guwus_btn_p'],
					hot:['worldboss_guwus_btn_h'],
					disable:['worldboss_guwus_btn_d']
					}
				}
			},
		mainvip:{type:0,
			   cls:{
				normal:['vip_btn_n'],
				press:['vip_btn_p'],
				hot:['vip_btn_h'],
				disable:['vip_btn_n']
			   }
			},
		suggest:{type:0,
			   cls:{
				normal:['suggest_btn_n'],
				press:['suggest_btn_p'],
				hot:['suggest_btn_h'],
				disable:['suggest_btn_n']
			   }
			},
		suggest_new:{type:0,
			   cls:{
				normal:['suggest_btn_n_new'],
				press:['suggest_btn_p'],
				hot:['suggest_btn_h'],
				disable:['suggest_btn_n']
			   }
			},
		payactpaybtn:{type:0,
			   cls:{
				normal:['ui-payact_paybtn-n'],
				press:['ui-payact_paybtn-p'],
				hot:['ui-payact_paybtn-h'],
				disable:['ui-payact_paybtn-d']
			   }
			},
		payactgetbtn:{type:0,
			   cls:{
				normal:['ui-payact_getbtn-n'],
				press:['ui-payact_getbtn-p'],
				hot:['ui-payact_getbtn-h'],
				disable:['ui-payact_getbtn-d']
			   }
			},
		bdclosebtn:{type:0,
			   cls:{
				normal:['bd-ui-closebtn-n'],
				press:['bd-ui-closebtn-p'],
				hot:['bd-ui-closebtn-h'],
				disable:['bd-ui-closebtn-n']
			   }
			},
		bdopenbdbtn:{type:0,
			   cls:{
				normal:['bd-ui-openbdbtn-n'],
				press:['bd-ui-openbdbtn-n'],
				hot:['bd-ui-openbdbtn-h'],
				disable:['bd-ui-openbdbtn-n']
			   }
			},
		bdpaybdbtn:{type:0,
			   cls:{
				normal:['bd-ui-paybdbtn-n'],
				press:['bd-ui-paybdbtn-n'],
				hot:['bd-ui-paybdbtn-h'],
				disable:['bd-ui-paybdbtn-n']
			   }
			},
		bdopenyearbdbtn:{type:0,
			   cls:{
				normal:['bd-ui-openyearbdbtn-n'],
				press:['bd-ui-openyearbdbtn-n'],
				hot:['bd-ui-openyearbdbtn-h'],
				disable:['bd-ui-openyearbdbtn-n']
			   }
			},
		bdpayyearbdbtn:{type:0,
			   cls:{
				normal:['bd-ui-payyearbdbtn-n'],
				press:['bd-ui-payyearbdbtn-n'],
				hot:['bd-ui-payyearbdbtn-h'],
				disable:['bd-ui-payyearbdbtn-n']
			   }
			},
		bdgetbtn:{type:0,
			   cls:{
				normal:['bd-ui-getbtn-n'],
				press:['bd-ui-getbtn-n'],
				hot:['bd-ui-getbtn-h'],
				disable:['bd-ui-getbtn-d']
			   }
			},
		bdbuybtn:{type:0,
			   cls:{
				normal:['bd-ui-buybtn-n'],
				press:['bd-ui-buybtn-n'],
				hot:['bd-ui-buybtn-h'],
				disable:['bd-ui-buybtn-n']
			   }
			},
			
		ydclosebtn:{type:0,
			   cls:{
				normal:['yb-ui-closebtn-n'],
				press:['yb-ui-closebtn-n'],
				hot:['yb-ui-closebtn-h'],
				disable:['yb-ui-closebtn-n']
			   }
			},
		ydbuybtn:{type:0,
			   cls:{
				normal:['yb-ui-buybtn-n'],
				press:['yb-ui-buybtn-n'],
				hot:['yb-ui-buybtn-h'],
				disable:['yb-ui-buybtn-n']
			   }
			},
		ydgetbtn:{type:0,
			   cls:{
				normal:['yb-ui-getbtn-n'],
				press:['yb-ui-getbtn-n'],
				hot:['yb-ui-getbtn-h'],
				disable:['yb-ui-getbtn-d']
			   }
			},
		ydimmgetbtn:{type:0,
			   cls:{
				normal:['yb-ui-immgetbtn-n'],
				press:['yb-ui-immgetbtn-n'],
				hot:['yb-ui-immgetbtn-h'],
				disable:['yb-ui-immgetbtn-d']
			   }
			},
		ydopenydbtn:{type:0,
			   cls:{
				normal:['yb-ui-openydbtn-n'],
				press:['yb-ui-openydbtn-n'],
				hot:['yb-ui-openydbtn-h'],
				disable:['yb-ui-openydbtn-n']
			   }
			},
		ydopenyearydbtn:{type:0,
			   cls:{
				normal:['yb-ui-openyearydbtn-n'],
				press:['yb-ui-openyearydbtn-n'],
				hot:['yb-ui-openyearydbtn-h'],
				disable:['yb-ui-openyearydbtn-n']
			   }
			},			
		ydpayydbtn:{type:0,
			   cls:{
				normal:['yb-ui-payydbtn-n'],
				press:['yb-ui-payydbtn-n'],
				hot:['yb-ui-payydbtn-h'],
				disable:['yb-ui-payydbtn-n']
			   }
			},			
		ydpayyearydbtn:{type:0,
			   cls:{
				normal:['yb-ui-payyearydbtn-n'],
				press:['yb-ui-payyearydbtn-n'],
				hot:['yb-ui-payyearydbtn-h'],
				disable:['yb-ui-payyearydbtn-n']
			   }
			},
			
		emptyBtn:{type:0,
			cls:{
				normal:['ui-emptybtn-n'],
				press:['ui-emptybtn-n'],
				hot:['ui-emptybtn-n'],
				disable:['ui-emptybtn-n']
				}
			},
		empty2Btn:{type:0,
			cls:{
				normal:['ui-emptybtn2-n'],
				press:['ui-emptybtn2-n'],
				hot:['ui-emptybtn2-n'],
				disable:['ui-emptybtn2-n']
				}
			},
			
		onlineTaskGet:	{type:0,
			   cls:{
				normal:['ui-onlinetaskget-n'],
				press:['ui-onlinetaskget-n'],
				hot:['ui-onlinetaskget-n'],
				disable:['ui-onlinetaskget-d']
			   }
			},
		onlineGoodsGet:	{type:0,
			   cls:{
				normal:['ui-onlinegoods-n'],
				press:['ui-onlinegoods-n'],
				hot:['ui-onlinegoods-n'],
				disable:['ui-onlinegoods-d']
			   }
			},
		lawlight:{
			upgrade:{
				type:0,
				cls:{
					normal:['ui-lawlight-upgrade-n'],
					press:['ui-lawlight-upgrade-p'],
					hot:['ui-lawlight-upgrade-h'],
					blinking:['ui-lawlight-upgrade-h'],
					disable:['ui-lawlight-upgrade-d']
			   }
			},
			bestow:{
				type:0,
				cls:{
					normal:['ui-lawlight-bestow-n'],
					press:['ui-lawlight-bestow-p'],
					hot:['ui-lawlight-bestow-h'],
					blinking:['ui-lawlight-bestow-h'],
					disable:['ui-lawlight-bestow-d']
			   }
			}
		},
		towervsbtn:{type:0,
			   cls:{
				normal:['ui-towervsbtn-n'],
				press:['ui-towervsbtn-p'],
				hot:['ui-towervsbtn-h'],
				disable:['ui-towervsbtn-d']
			   }
			},
		terracegatebtn:{type:0,
			   cls:{
				normal:['ui-terracegatebtn-n'],
				press:['ui-terracegatebtn-p'],
				hot:['ui-terracegatebtn-h'],
				disable:['ui-terracegatebtn-d']
			   }			
			},
		forIE6Terracegatebtn:{type:0,
			   cls:{
				normal:['ui-forie6terracegatebtn-n'],
				press:['ui-forie6terracegatebtn-p'],
				hot:['ui-forie6terracegatebtn-h'],
				disable:['ui-forie6terracegatebtn-d']
			   }			
			},
		terraceenterbtn:{type:0,
			   cls:{
				normal:['ui-terraceenterbtn-n'],
				press:['ui-terraceenterbtn-p'],
				hot:['ui-terraceenterbtn-h'],
				disable:['ui-terraceenterbtn-d']
			   }			
			},
		terraceprebtn:{type:0,
			   cls:{
				normal:['ui-terraceprebtn-n'],
				press:['ui-terraceprebtn-p'],
				hot:['ui-terraceprebtn-h'],
				disable:['ui-terraceprebtn-d']
			   }			
			},
		terracenextbtn:{type:0,
			   cls:{
				normal:['ui-terracenextbtn-n'],
				press:['ui-terracenextbtn-p'],
				hot:['ui-terracenextbtn-h'],
				disable:['ui-terracenextbtn-d']
			   }			
			},
		maintoolbtn:{type:0,
			   cls:{
				normal:['ui-maintoolbtn-n'],
				press:['ui-maintoolbtn-p'],
				hot:['ui-maintoolbtn-h'],
				blinking:['ui-maintoolbtn-b'],
				disable:['ui-maintoolbtn-n']
			   }
			},
		mbtn:{
			role:{
				type:0,
				newFlag:{pos:{x:50, y:5}, cls:'ui-mbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:1, y:1}, hot:{x:-2, y:-2},blinking:{x:-2, y:-2}}},
				cls:{
					normal:['ui-mbtn-role-n'],
					press:['ui-mbtn-role-p'],
					hot:['ui-mbtn-role-h'],
					blinking:['ui-mbtn-role-h'],
					disable:['ui-mbtn-role-h']
			   }
			},
			task:{
				type:0,
				newFlag:{pos:{x:35, y:5}, cls:'ui-mbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:1, y:1}, hot:{x:-2, y:-2},blinking:{x:-2, y:-2}}},
				cls:{
					normal:['ui-mbtn-task-n'],
					press:['ui-mbtn-task-p'],
					hot:['ui-mbtn-task-h'],
					blinking:['ui-mbtn-task-h'],
					disable:['ui-mbtn-task-h']
			   }
			},
			hero:{
				type:0,
				newFlag:{cls:'ui-mbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:1, y:1}, hot:{x:-2, y:-2},blinking:{x:-2, y:-2}}},
				cls:{
					normal:['ui-mbtn-hero-n'],
					press:['ui-mbtn-hero-p'],
					hot:['ui-mbtn-hero-h'],
					blinking:['ui-mbtn-hero-h'],
					disable:['ui-mbtn-hero-h']
			   }
			},
			alli:{
				type:0,
				newFlag:{cls:'ui-mbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:1, y:1}, hot:{x:-2, y:-2},blinking:{x:-2, y:-2}}},
				cls:{
					normal:['ui-mbtn-alli-n'],
					press:['ui-mbtn-alli-p'],
					hot:['ui-mbtn-alli-h'],
					blinking:['ui-mbtn-alli-h'],
					disable:['ui-mbtn-alli-h']
			   }
			},
			exped:{
				type:0,
				newFlag:{cls:'ui-mbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:1, y:1}, hot:{x:-2, y:-2},blinking:{x:-2, y:-2}}},
				cls:{
					normal:['ui-mbtn-exped-n'],
					press:['ui-mbtn-exped-p'],
					hot:['ui-mbtn-exped-h'],
					blinking:['ui-mbtn-exped-h'],
					disable:['ui-mbtn-exped-h']
			   }
			},
			military:{
				type:0,
				newFlag:{pos:{x:50, y:5}, cls:'ui-mbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:1, y:1}, hot:{x:-2, y:-2},blinking:{x:-2, y:-2}}},
				cls:{
					normal:['ui-mbtn-military-n'],
					press:['ui-mbtn-military-p'],
					hot:['ui-mbtn-military-h'],
					blinking:['ui-mbtn-military-h'],
					disable:['ui-mbtn-military-h']
			   }
			},
			pkg:{
				type:0,
				newFlag:{cls:'ui-mbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:1, y:1}, hot:{x:-2, y:-2},blinking:{x:-2, y:-2}}},
				cls:{
					normal:['ui-mbtn-pkg-n'],
					press:['ui-mbtn-pkg-p'],
					hot:['ui-mbtn-pkg-h'],
					blinking:['ui-mbtn-pkg-h'],
					disable:['ui-mbtn-pkg-h']
			   }
			}
		},
		smbtn:{
			shop:{
				type:0,
				cls:{
					normal:['ui-smbtn-shop-n'],
					press:['ui-smbtn-shop-p'],
					hot:['ui-smbtn-shop-h'],
					blinking:['ui-smbtn-shop-h'],
					disable:['ui-smbtn-shop-n']
			   }
			},
			rank:{
				type:0,
				cls:{
					normal:['ui-smbtn-rank-n'],
					press:['ui-smbtn-rank-p'],
					hot:['ui-smbtn-rank-h'],
					blinking:['ui-smbtn-rank-h'],
					disable:['ui-smbtn-rank-n']
			   }
			},
			letter:{
				type:0,
				newFlag:{cls:'ui-smbtn-reddot'},
				cls:{
					normal:['ui-smbtn-letter-n'],
					press:['ui-smbtn-letter-p'],
					hot:['ui-smbtn-letter-h'],
					blinking:['ui-smbtn-letter-h'],
					disable:['ui-smbtn-letter-n']
			   }
			},
			exchange:{
				type:0,
				newFlag:{cls:'ui-smbtn-reddot'},
				cls:{
					normal:['ui-smbtn-exchange-n'],
					press:['ui-smbtn-exchange-p'],
					hot:['ui-smbtn-exchange-h'],
					blinking:['ui-smbtn-exchange-h'],
					disable:['ui-smbtn-exchange-n']
			   }
			},
			sound:{
				type:0,
				cls:{
					normal:['ui-smbtn-sound-n'],
					press:['ui-smbtn-sound-p'],
					hot:['ui-smbtn-sound-h'],
					blinking:['ui-smbtn-sound-h'],
					disable:['ui-smbtn-sound-n']
			   }
			}
		},
		createrole:{
			enter:{
				type:0,
				cls:{
					normal:['ui-crbtn-enter-n'],
					press:['ui-crbtn-enter-p'],
					hot:['ui-crbtn-enter-h'],
					disable:['ui-crbtn-enter-d']
			   }
			}
		},
		skipfightbtn:{type:0,
			   cls:{
				normal:['ui-skipfightbtn-n'],
				press:['ui-skipfightbtn-p'],
				hot:['ui-skipfightbtn-h'],
				disable:['ui-skipfightbtn-n']
			   }
			},
		citylevelupbtn:{type:0,
			   cls:{
				normal:['ui-citylevelupbtn-n'],
				press:['ui-citylevelupbtn-p'],
				hot:['ui-citylevelupbtn-h'],
				blinking:['ui-citylevelupbtn-h'],
				disable:['ui-citylevelupbtn-d']
			   }
			},
		assignheros:{type:0,
			   cls:{
				normal:['ui-assignherosbtn-n'],
				press:['ui-assignherosbtn-p'],
				hot:['ui-assignherosbtn-h'],
				disable:['ui-assignherosbtn-n']
			   }
			},
		expedition:{type:0,
			   cls:{
				normal:['ui-expeditionbtn-n'],
				press:['ui-expeditionbtn-p'],
				hot:['ui-expeditionbtn-h'],
				disable:['ui-expeditionbtn-n']
			   }
			},
		selectexpetarget:{type:0,
			   cls:{
				normal:['ui-selectexpetargetbtn-n'],
				press:['ui-selectexpetargetbtn-p'],
				hot:['ui-selectexpetargetbtn-h'],
				disable:['ui-selectexpetargetbtn-n']
			   }
			},
		worldmap:{type:0,
			   cls:{
				normal:['ui-worldmapbtn-n'],
				press:['ui-worldmapbtn-p'],
				hot:['ui-worldmapbtn-h'],
				disable:['ui-worldmapbtn-n']
			   }
			},
		fixminitab:{
			type:0,
			   cls:{
				normal:['ui-fixminitabbtn-n'],
				press:['ui-fixminitabbtn-p'],
				hot:['ui-fixminitabbtn-h'],
				disable:['ui-fixminitabbtn-n']
			   }
			},
		selcitybtn:{type:0,
			   newFlag:{pos:{x:58, y:5}, cls:'ui-smbtn-reddot'},
			   cls:{
				normal:['ui-selcitybtn-n'],
				press:['ui-selcitybtn-p'],
				hot:['ui-selcitybtn-h'],
				disable:['ui-selcitybtn-n']
			   }
			},
		rechargebtn:{type:0,
			   cls:{
				normal:['ui-rechargebtn-n'],
				press:['ui-rechargebtn-p'],
				hot:['ui-rechargebtn-h'],
				disable:['ui-rechargebtn-n']
			   }
			},
		officialbtn:{type:0,
			   cls:{
				normal:['ui-officialbtn-n'],
				press:['ui-officialbtn-p'],
				hot:['ui-officialbtn-h'],
				disable:['ui-officialbtn-n']
			   }
			},
		gonggaobtn:{type:0,
			   cls:{
				normal:['ui-gonggaobtn-n'],
				press:['ui-gonggaobtn-p'],
				hot:['ui-gonggaobtn-h'],
				disable:['ui-gonggaobtn-n']
			   }
			},
		trackbtn:{
			task:{
				type:0,
				cls:{
					normal:['ui-trackbtn-task-n'],
					press:['ui-trackbtn-task-p'],
					hot:['ui-trackbtn-task-h'],
					disable:['ui-trackbtn-task-n']
			   }			
			},
			actdate:{
				type:0,
				newFlag:{cls:'ui-trackbtn-reddot', offsets:{normal:{x:0, y:0}, press:{x:-1, y:-1}, hot:{x:-1, y:-1}}},
				cls:{
					normal:['ui-trackbtn-actdate-n'],
					press:['ui-trackbtn-actdate-p'],
					hot:['ui-trackbtn-actdate-h'],
					disable:['ui-trackbtn-actdate-n']
			   }				
			},
			autobuild:{
				type:0,
				newFlag:{cls:'ui-trackbtn-reddot', pos:{x:20, y:2}, offsets:{normal:{x:0, y:0}, press:{x:-1, y:-1}, hot:{x:-1, y:-1}}},
				cls:{
					normal:['ui-trackbtn-autobuild-n'],
					press:['ui-trackbtn-autobuild-p'],
					hot:['ui-trackbtn-autobuild-h'],
					disable:['ui-trackbtn-autobuild-n']
			   }				
			},
			building:{
				type:0,
				cls:{
					normal:['ui-trackbtn-building-n'],
					press:['ui-trackbtn-building-p'],
					hot:['ui-trackbtn-building-h'],
					disable:['ui-trackbtn-building-n']
			   }				
			}
		},
		addbtn:{type:0,
			   cls:{
				normal:['ui-addbtn-n'],
				press:['ui-addbtn-p'],
				hot:['ui-addbtn-h'],
				disable:['ui-addbtn-d']
			   }
			},
		subbtn:{type:0,
			   cls:{
				normal:['ui-subbtn-n'],
				press:['ui-subbtn-p'],
				hot:['ui-subbtn-h'],
				disable:['ui-subbtn-d']
			   }
			},
		search:{type:0,
			   cls:{
				normal:['ui-searchbtn-n'],
				press:['ui-searchbtn-p'],
				hot:['ui-searchbtn-h'],
				disable:['ui-searchbtn-n']
			   }
			},
		color:{type:0,
			   cls:{
				normal:['ui-colorbtn-n'],
				press:['ui-colorbtn-p'],
				hot:['ui-colorbtn-h'],
				disable:['ui-colorbtn-n']
			   }
			},
		face:{type:0,
			   cls:{
				normal:['ui-facebtn-n'],
				press:['ui-facebtn-p'],
				hot:['ui-facebtn-h'],
				disable:['ui-facebtn-n']
			   }
		   },
		font:{type:0,
			   cls:{
				normal:['ui-fontbtn-n'],
				press:['ui-fontbtn-p'],
				hot:['ui-fontbtn-h'],
				disable:['ui-fontbtn-n']
			   }
		   },
		clearchat:{type:0,
			   cls:{
				normal:['ui-clearchatbtn-n'],
				press:['ui-clearchatbtn-p'],
				hot:['ui-clearchatbtn-h'],
				disable:['ui-clearchatbtn-n']
			   }
		   },
		chatsend:{type:0,
			   cls:{
				normal:['ui-chatsend-n'],
				press:['ui-chatsend-p'],
				hot:['ui-chatsend-h'],
				disable:['ui-chatsend-n']
			   }
			},
		chattarget:{type:0,
			   cls:{
				normal:['ui-chattarget-n'],
				press:['ui-chattarget-n'],
				hot:['ui-chattarget-h'],
				disable:['ui-chattarget-n']
			   }
			},
		chatexpend:{type:0,
			   cls:{
				normal:['ui-chatexpend-n'],
				press:['ui-chatexpend-p'],
				hot:['ui-chatexpend-h'],
				disable:['ui-chatexpend-n']
			   }
			},
		check:{type:0,
			   cls:{
				normal:['ui-checkbox-n'],
				press:['ui-checkbox-p'],
				hot:['ui-checkbox-h'],
				disable:['ui-checkbox-n']
			   }
			},
		dlgbtn:{type:1,
			   cls:{
				normal:['ui-combtn-1-n', 'ui-combtn-2-n', 'ui-combtn-3-n'],
				press:['ui-combtn-1-p', 'ui-combtn-2-p', 'ui-combtn-3-p'],
				hot:['ui-combtn-1-h', 'ui-combtn-2-h', 'ui-combtn-3-h'],
				disable:['ui-combtn-1-d', 'ui-combtn-2-d', 'ui-combtn-3-d']
			   }
			},
		dlgclose:{type:0,
			   cls:{
				normal:['ui-dlg-close-n'],
				press:['ui-dlg-close-p'],
				hot:['ui-dlg-close-h'],
				disable:['ui-dlg-close-n']
			   }
			},
		dlgclose2:{type:0,
			   cls:{
				normal:['ui-dlg-close2-n'],
				press:['ui-dlg-close2-p'],
				hot:['ui-dlg-close2-h'],
				disable:['ui-dlg-close2-n']
			   }
			},
		dlgclose3:{type:0,
			   cls:{
				normal:['ui-dlg-close3-n'],
				press:['ui-dlg-close3-p'],
				hot:['ui-dlg-close3-h'],
				disable:['ui-dlg-close3-n']
			   }
			},
		dlgclose4:{type:0,
			   cls:{
				normal:['ui-dlg-close4-n'],
				press:['ui-dlg-close4-p'],
				hot:['ui-dlg-close4-h'],
				disable:['ui-dlg-close4-n']
			   }
			},
		dlgclose5:{type:0,
			   cls:{
				normal:['ui-dlg-close5-n'],
				press:['ui-dlg-close5-p'],
				hot:['ui-dlg-close5-h'],
				disable:['ui-dlg-close5-n']
			   }
			},
		replay:{type:0,
			   cls:{
				normal:['ui-replaybtn-n'],
				press:['ui-replaybtn-p'],
				hot:['ui-replaybtn-h'],
				disable:['ui-replaybtn-n']
			   }
			},
		commtoggle:{type:0,
			   cls:{
				normal:['ui-win-commtoggle-n'],
				press:['ui-win-commtoggle-p'],
				presshot:['ui-win-commtoggle-ph'],
				hot:['ui-win-commtoggle-h'],
				disable:['ui-win-commtoggle-n']
			   }
			},
		friendListtoggle:{type:0,
			   cls:{
				normal:['ui-friendListtoggle-n'],
				hot:['ui-friendListtoggle-h'],
				blinking:['ui-friendListtoggle-b'],
				press:['ui-friendListtoggle-p'],
				presshot:['ui-friendListtoggle-ph'],
				pressblinking:['ui-friendListtoggle-pb'],
				disable:['ui-friendListtoggle-n']
			   }
			},
		dlghelp:{type:0,
			   cls:{
				normal:['ui-dlg-help-n'],
				press:['ui-dlg-help-p'],
				hot:['ui-dlg-help-h'],
				disable:['ui-dlg-help-n']
			   }
			},
		tabbtn:{type:1,
				newFlag:{cls:'ui-tabbtn-reddot'},
			   cls:{
				normal:['ui-tabbtn-1-n', 'ui-tabbtn-2-n', 'ui-tabbtn-3-n'],
				press:['ui-tabbtn-1-p', 'ui-tabbtn-2-p', 'ui-tabbtn-3-p'],
				hot:['ui-tabbtn-1-h', 'ui-tabbtn-2-h', 'ui-tabbtn-3-h'],
				disable:['ui-tabbtn-1-n', 'ui-tabbtn-2-n', 'ui-tabbtn-3-n']
			   }
			},
		mintab:{type:1,
			   cls:{
				normal:['ui-mintab-1-n', 'ui-mintab-2-n', 'ui-mintab-3-n'],
				press:['ui-mintab-1-p', 'ui-mintab-2-p', 'ui-mintab-3-p'],
				hot:['ui-mintab-1-h', 'ui-mintab-2-h', 'ui-mintab-3-h'],
				disable:['ui-mintab-1-n', 'ui-mintab-2-n', 'ui-mintab-3-n']
			   }
			},
		chatchanneltab:{type:0,
			   cls:{
				normal:['ui-chatchanneltab-n'],
				press:['ui-chatchanneltab-h'],
				hot:['ui-chatchanneltab-h'],
				disable:['ui-chatchanneltab-n']
			   }
			},
		qiandao:{type:0,
			   cls:{
				normal:['ui-qiandaobtn-n'],
				press:['ui-qiandaobtn-p'],
				hot:['ui-qiandaobtn-h'],
				disable:['ui-qiandaobtn-d']
			   }
			},
		minbtn:{type:1,
			   cls:{
				normal:['ui-minbtn-1-n', 'ui-minbtn-2-n', 'ui-minbtn-3-n'],
				press:['ui-minbtn-1-p', 'ui-minbtn-2-p', 'ui-minbtn-3-p'],
				hot:['ui-minbtn-1-h', 'ui-minbtn-2-h', 'ui-minbtn-3-h'],
				disable:['ui-minbtn-1-d', 'ui-minbtn-2-d', 'ui-minbtn-3-d']
			   }
			},
		fixminbtn_2hz:{type:0,
			   cls:{
				normal:['ui-fixminbtn-2hz-n'],
				press:['ui-fixminbtn-2hz-p'],
				hot:['ui-fixminbtn-2hz-h'],
				disable:['ui-fixminbtn-2hz-d']
			   }
			},
		fixminbtn_3hz:{type:0,
			   cls:{
				normal:['ui-fixminbtn-3hz-n'],
				press:['ui-fixminbtn-3hz-p'],
				hot:['ui-fixminbtn-3hz-h'],
				disable:['ui-fixminbtn-3hz-d']
			   }
			},
		fixminbtn_4hz:{type:0,
			   cls:{
				normal:['ui-fixminbtn-4hz-n'],
				press:['ui-fixminbtn-4hz-p'],
				hot:['ui-fixminbtn-4hz-h'],
				disable:['ui-fixminbtn-4hz-d']
			   }
			},
		fixminbtn2_4hz:{type:0,
			   cls:{
				normal:['ui-fixminbtn2-4hz-n'],
				press:['ui-fixminbtn2-4hz-p'],
				hot:['ui-fixminbtn2-4hz-h'],
				disable:['ui-fixminbtn2-4hz-n']
			   }
			},
		leftexpand:{type:0,
			   cls:{
				normal:['ui-leftexpandbtn-n'],
				press:['ui-leftexpandbtn-p'],
				hot:['ui-leftexpandbtn-h'],
				disable:['ui-leftexpandbtn-d']
			   }
			},
		leftcollapse:{type:0,
			   cls:{
				normal:['ui-leftcollapsebtn-n'],
				press:['ui-leftcollapsebtn-p'],
				hot:['ui-leftcollapsebtn-h'],
				disable:['ui-leftcollapsebtn-d']
			   }
			},
		scrollbar:{type:0,
			   cls:{
				normal:['ui-scrollbar'],
				press:['ui-scrollbar'],
				hot:['ui-scrollbar'],
				disable:['ui-scrollbar']
			   }
			},
		droptitle:{type:0,
			   cls:{
				normal:['title-n'],
				press:['title-p'],
				hot:['title-h'],
				disable:['title-n']
			   }
			},
		droparraw:{type:0,
			   cls:{
				normal:['arraw-n'],
				press:['arraw-p'],
				hot:['arraw-h'],
				disable:['arraw-n']
			   }
			},
		pagefirst:{type:0,
			   cls:{
				normal:['page_first_n'],
				press:['page_first_p'],
				hot:['page_first_h'],
				disable:['page_first_d']
			   }
			},
		pageprev:{type:0,
			   cls:{
				normal:['page_prev_n'],
				press:['page_prev_p'],
				hot:['page_prev_h'],
				disable:['page_prev_d']
			   }
			},
		pagenext:{type:0,
			   cls:{
				normal:['page_next_n'],
				press:['page_next_p'],
				hot:['page_next_h'],
				disable:['page_next_d']
			   }
			},
		pagelast:{type:0,
			   cls:{
				normal:['page_last_n'],
				press:['page_last_p'],
				hot:['page_last_h'],
				disable:['page_last_d']
			   }
			},
		prev2btn:{type:0,
			   cls:{
				normal:['ui_prev2_n'],
				press:['ui_prev2_p'],
				hot:['ui_prev2_h'],
				disable:['ui_prev2_n']
			   }
			},
		next2btn:{type:0,
			   cls:{
				normal:['ui_next2_n'],
				press:['ui_next2_p'],
				hot:['ui_next2_h'],
				disable:['ui_next2_n']
			   }
			},
		scrollubtn:{type:0,
			   cls:{
				normal:['ui-scrollubtn-n'],
				press:['ui-scrollubtn-n'],
				hot:['ui-scrollubtn-n'],
				disable:['ui-scrollubtn-n']
			   }
			},
		scrolldbtn:{type:0,
			   cls:{
				normal:['ui-scrolldbtn-n'],
				press:['ui-scrolldbtn-n'],
				hot:['ui-scrolldbtn-n'],
				blinking:['ui-scrolldbtn-b'],
				disable:['ui-scrolldbtn-n']
			   }
			},
		spinprev:{type:0,
			   cls:{
				normal:['prev-n'],
				press:['prev-p'],
				hot:['prev-h'],
				disable:['prev-n']
			   }
			},
		spinnext:{type:0,
			   cls:{
				normal:['next-n'],
				press:['next-p'],
				hot:['next-h'],
				disable:['next-n']
			   }
			},
		linebtn:{type:0,
			   cls:{
				normal:['ui-line-btn-n'],
				press:['ui-line-btn-p'],
				hot:['ui-line-btn-h'],
				disable:['ui-line-btn-d']
			   }
			},
		blinebtn:{type:0,
			   cls:{
				normal:['ui-bline-btn-n'],
				press:['ui-bline-btn-p'],
				hot:['ui-bline-btn-h'],
				disable:['ui-bline-btn-n']
			   }
			},
		exlinebtn:{type:0,
			   cls:{
				normal:['external ui-line-btn-n'],
				press:['external ui-line-btn-p'],
				hot:['external ui-line-btn-h'],
				disable:['external ui-line-btn-n']
			   }
			},
		tasktrackjump:{type:0,
			   cls:{
				normal:['ui-dlg-close-n'],
				press:['ui-dlg-close-p'],
				hot:['ui-dlg-close-h'],
				disable:['ui-dlg-close-n']
			   }
			},
		delbtn:{type:0,
			   cls:{
				normal:['ui-deletebtn-n'],
				press:['ui-deletebtn-p'],
				hot:['ui-deletebtn-h'],
				disable:['ui-deletebtn-n']
			   }
			},
		helpspirit:{type:0,
			   cls:{
				normal:['ui-spirit-min-n'],
				press:['ui-spirit-min-p'],
				hot:['ui-spirit-min-h'],
				disable:['ui-spirit-min-n']
			   }
			},
		queuemsg:{type:0,
			   cls:{
				normal:['ui-spirit-min-n'],
				press:['ui-spirit-min-p'],
				hot:['ui-spirit-min-h'],
				disable:['ui-spirit-min-n']
			   }
			},
		teamgroup:{type:0,
			   cls:{
				normal:['ui-teamgroup-n'],
				press:['ui-teamgroup-p'],
				hot:['ui-teamgroup-h'],
				disable:['ui-teamgroup-n']
			   }
			},
		plusbtn:{type:0,
			   cls:{
				normal:['ui-plusbtn-n'],
				press:['ui-plusbtn-p'],
				hot:['ui-plusbtn-h'],
				disable:['ui-plusbtn-n']
			   }
			}
		,block:{type:0,
			   cls:{
				normal:['ui-block-btn-n'],
				press:['ui-block-btn-p'],
				hot:['ui-block-btn-h'],
				disable:['ui-block-btn-d']
			   }
			}
		,fcancel:{type:0,
			   cls:{
				normal:['ui-fcancel-btn-n'],
				press:['ui-fcancel-btn-p'],
				hot:['ui-fcancel-btn-h'],
				disable:['ui-fcancel-btn-n']
			   }
			}
		,friend:{
			applyList:{
				type:0,
				cls:{
					normal:['friend-applyList-btn-n'],
					press:['friend-applyList-btn-p'],
					hot:['friend-applyList-btn-h'],
					blinking:['friend-applyList-btn-b'],
					disable:['friend-applyList-btn-n']
			   }
			}
		}
		,subCityBtns:{
			resBtn:{
				type:0,
				cls:{
					normal:['ui-subcityresbtn-n'],
					press:['ui-subcityresbtn-p'],
					hot:['ui-subcityresbtn-h'],
					disable:['ui-subcityresbtn-n']
			   }
			}
			,militaryBtn:{
				type:0,
				cls:{
					normal:['ui-subcitymilitarybtn-n'],
					press:['ui-subcitymilitarybtn-p'],
					hot:['ui-subcitymilitarybtn-h'],
					disable:['ui-subcitymilitarybtn-n']
			   }
			}
			,emptyBtn:{
				type:0,
				cls:{
					normal:['ui-subcityemptybtn-n'],
					press:['ui-subcityemptybtn-n'],
					hot:['ui-subcityemptybtn-h'],
					disable:['ui-subcityemptybtn-d']
			   }
			}
			,fieldBtn:{
				type:0,
				cls:{
					normal:['ui-selffieldbtn-n'],
					press:['ui-selffieldbtn-n'],
					hot:['ui-selffieldbtn-h'],
					disable:['ui-selffieldbtn-d']
			   }			
			}
		}
		,farm:{
				ops:{
					sel:{
						type:0,
						cls:{
						normal:['opsel-btn-n'],
						press:['opsel-btn-p'],
						hot:['opsel-btn-h'],
						disable:['opsel-btn-n']
					   }
					}
					,input:{
						type:0,
						cls:{
						normal:['opinput-btn-n'],
						press:['opinput-btn-p'],
						hot:['opinput-btn-h'],
						disable:['opinput-btn-n']
					   }
					}
					,init:{
						type:0,
						cls:{
						normal:['opinit-btn-n'],
						press:['opinit-btn-p'],
						hot:['opinit-btn-h'],
						disable:['opinit-btn-n']
					   }
					}
					,get:{
						type:0,
						cls:{
						normal:['opget-btn-n'],
						press:['opget-btn-p'],
						hot:['opget-btn-h'],
						disable:['opget-btn-n']
					   }
					}
					,pre:{
						type:0,
						cls:{
						normal:['oppre-btn-n'],
						press:['oppre-btn-p'],
						hot:['oppre-btn-h'],
						disable:['oppre-btn-n']
					   }
					}
					,all:{
						type:0,
						cls:{
						normal:['opall-btn-n'],
						press:['opall-btn-p'],
						hot:['opall-btn-h'],
						disable:['opall-btn-n']
					   }
					}
					,otherget:{
						type:0,
						cls:{
						normal:['opotherget-btn-n'],
						press:['opotherget-btn-p'],
						hot:['opotherget-btn-h'],
						disable:['opotherget-btn-n']
					   }
					}
					,otherall:{
						type:0,
						cls:{
						normal:['opotherall-btn-n'],
						press:['opotherall-btn-p'],
						hot:['opotherall-btn-h'],
						disable:['opotherall-btn-n']
					   }
					}					
					,myfarm:{
						type:0,
						cls:{
						normal:['opmyfarm-btn-n'],
						press:['opmyfarm-btn-p'],
						hot:['opmyfarm-btn-h'],
						disable:['opmyfarm-btn-n']
					   }
					}
					,farminfo:{
						type:0,
						cls:{
						normal:['opfarminfo-btn-n'],
						press:['opfarminfo-btn-p'],
						hot:['opfarminfo-btn-h'],
						disable:['opfarminfo-btn-n']
					   }
					}
					,farmrefresh:{
						type:0,
						cls:{
						normal:['opfarmrefresh-btn-n'],
						press:['opfarmrefresh-btn-p'],
						hot:['opfarmrefresh-btn-h'],
						disable:['opfarmrefresh-btn-n']
					   }
					}
					,farmrule:{
						type:0,
						cls:{
						normal:['opfarmrule-btn-n'],
						press:['opfarmrule-btn-p'],
						hot:['opfarmrule-btn-h'],
						disable:['opfarmrule-btn-n']
					   }
					}
					,openfriend:{
						type:0,
						cls:{
						normal:['openfriend-btn-n'],
						press:['openfriend-btn-p'],
						hot:['openfriend-btn-h'],
						disable:['openfriend-btn-n']
					   }
					}
					,closefriend:{
						type:0,
						cls:{
						normal:['closefriend-btn-n'],
						press:['closefriend-btn-p'],
						hot:['closefriend-btn-h'],
						disable:['closefriend-btn-n']
					   }
					}
				}
			}
		,field:{
			homebtn:{type:0,
			   cls:{
				normal:['ui-fieldgohomebtn-n'],
				press:['ui-fieldgohomebtn-p'],
				hot:['ui-fieldgohomebtn-h'],
				disable:['ui-fieldgohomebtn-n']
			   }
			}
			,gotobtn:{type:0,
			   cls:{
				normal:['ui-fieldgotobtn-n'],
				press:['ui-fieldgotobtn-p'],
				hot:['ui-fieldgotobtn-h'],
				disable:['ui-fieldgotobtn-n']
			   }
			}
		}
		,activityVal:{
			nolink_nofinish:{
				type:0,
				cls:{
					normal:['ui-nolink-nofinish-line-btn-n'],
					press:['ui-nolink-nofinish-line-btn-n'],
					hot:['ui-nolink-nofinish-line-btn-n'],
					disable:['ui-nolink-nofinish-line-btn-n']
				   }
			}
			,nolink_finishpart:{
				type:0,
				cls:{
					normal:['ui-nolink-finishpart-line-btn-n'],
					press:['ui-nolink-finishpart-line-btn-n'],
					hot:['ui-nolink-finishpart-line-btn-n'],
					disable:['ui-nolink-finishpart-line-btn-n']
				   }				
			}
			,nolink_finish:{
				type:0,
				cls:{
					normal:['ui-nolink-finish-line-btn-n'],
					press:['ui-nolink-finish-line-btn-n'],
					hot:['ui-nolink-finish-line-btn-n'],
					disable:['ui-nolink-finish-line-btn-n']
				   }				
			}
			,link_nofinish:{
				type:0,
				cls:{
					normal:['ui-link-nofinish-line-btn-n'],
					press:['ui-link-nofinish-line-btn-p'],
					hot:['ui-link-nofinish-line-btn-h'],
					disable:['ui-link-nofinish-line-btn-d']
				   }				
			}
			,link_finishpart:{
				type:0,
				cls:{
					normal:['ui-link-finishpart-line-btn-n'],
					press:['ui-link-finishpart-line-btn-p'],
					hot:['ui-link-finishpart-line-btn-h'],
					disable:['ui-link-finishpart-line-btn-d']
				   }
			}
			,nolink_title:{
				type:0,
				cls:{
					normal:['ui-nolink-title-line-btn-n'],
					press:['ui-nolink-title-line-btn-n'],
					hot:['ui-nolink-title-line-btn-n'],
					disable:['ui-nolink-title-line-btn-n']
				   }
			}
			,actReward_canGet:{
				type:0,
				cls:{
					normal:['ui-actreward-canget-line-btn-n'],
					press:['ui-actreward-canget-line-btn-p'],
					hot:['ui-actreward-canget-line-btn-h'],
					disable:['ui-actreward-canget-line-btn-d']
				   }				
			}
			,actReward_noEnough:{
				type:0,
				cls:{
					normal:['ui-actreward-noenough-line-btn-n'],
					press:['ui-actreward-noenough-line-btn-n'],
					hot:['ui-actreward-noenough-line-btn-n'],
					disable:['ui-actreward-noenough-line-btn-n']
				   }
			}
			,actReward_got:{
				type:0,
				cls:{
					normal:['ui-actreward-got-line-btn-n'],
					press:['ui-actreward-got-line-btn-n'],
					hot:['ui-actreward-got-line-btn-n'],
					disable:['ui-actreward-got-line-btn-n']
				   }
			}
		}
	}
};