var res_skillclts = [
	{
		id:6001001,
		dist:0,
		prephase:{
			action:{
				wait:0,//在该动作开始需等待的时长
				name:'prepare',//将要播放的动作名称
				duration:1000//该动作将持续的时长
			},
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100001,//将要播放的特效id
				duration:1000//该特效将持续的时长
			},
			event:{
				wait:1000//该事件等待多长后被触发，启动下个阶段
			}
		},
		atkphase:{
			action:{
				wait:0,//在该动作开始需等待的时长
				name:'attack',//将要播放的动作名称
				duration:1000//该动作将持续的时长
			},
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100002,//将要播放的特效id
				duration:1000//该特效将持续的时长
			},
			event:{
				wait:1000//该事件等待多长后被触发，启动下个阶段
			}
		},
		flyphase:{
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100005,//将要播放的特效id
				speed:150//该特效的飞行速度
			}
		},
		hitphase:[
			{   // 普通攻击，或默认表现
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:100003,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			},
			{   // 暴击
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:100004,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			},
			{   // 免疫
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				/*
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:001,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				*/
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			}
		]
	}
	,	{
		id:6001002,
		dist:0,
		prephase:{
			action:{
				wait:0,//在该动作开始需等待的时长
				name:'prepare',//将要播放的动作名称
				duration:1000//该动作将持续的时长
			},
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100001,//将要播放的特效id
				duration:1000//该特效将持续的时长
			},
			event:{
				wait:1000//该事件等待多长后被触发，启动下个阶段
			}
		},
		atkphase:{
			action:{
				wait:0,//在该动作开始需等待的时长
				name:'attack',//将要播放的动作名称
				duration:1000//该动作将持续的时长
			},
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100002,//将要播放的特效id
				duration:1000//该特效将持续的时长
			},
			event:{
				wait:1000//该事件等待多长后被触发，启动下个阶段
			}
		},
		flyphase:{
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100005,//将要播放的特效id
				speed:50//该特效的飞行速度
			}
		},
		hitphase:[
			{   // 普通攻击，或默认表现
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:100003,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			},
			{   // 暴击
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:100004,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			},
			{   // 免疫
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				/*
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:001,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				*/
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			}
		]
	}
	,	{
		id:6001003,
		dist:0,
		prephase:{
			action:{
				wait:0,//在该动作开始需等待的时长
				name:'prepare',//将要播放的动作名称
				duration:1000//该动作将持续的时长
			},
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100001,//将要播放的特效id
				duration:1000//该特效将持续的时长
			},
			event:{
				wait:1000//该事件等待多长后被触发，启动下个阶段
			}
		},
		atkphase:{
			action:{
				wait:0,//在该动作开始需等待的时长
				name:'attack',//将要播放的动作名称
				duration:1000//该动作将持续的时长
			},
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100002,//将要播放的特效id
				duration:1000//该特效将持续的时长
			},
			event:{
				wait:1000//该事件等待多长后被触发，启动下个阶段
			}
		},
		flyphase:{
			effect:{
				wait:0,//在该特效开始需等待的时长
				id:100005,//将要播放的特效id
				speed:50//该特效的飞行速度
			}
		},
		hitphase:[
			{   // 普通攻击，或默认表现
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:100003,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			},
			{   // 暴击
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:100004,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			},
			{   // 免疫
				action:{
					wait:0,//在该动作开始需等待的时长
					name:'hit',//将要播放的动作名称
					duration:1000//该动作将持续的时长
				},
				/*
				effect:{
					wait:0,//在该特效开始需等待的时长
					id:001,//将要播放的特效id
					duration:1000//该特效将持续的时长
				},
				*/
				event:{
					wait:500//该事件等待多长后被触发，启动飘血效果
				}
			}
		]
	}
];