#ifndef _DBGLUA_H__
#define _DBGLUA_H__

static const char* s_szDbgLua =
"tqdb_exec_retval = nil															\n"
"-- 获取当前被调试函数的运行环境												\n"
"--@param savewhat																\n"
"-- 是否返回运行环境中函数具体的位置，提供tqdb_save_vars使用					\n"
"--@return vars,iupvars,ilocalvars												\n"
"--	vars 获取的运行环境															\n"
"--  iupvars 获取当前被调试函数的上行函数环境的位置信息							\n"
"--  ilocalvars 获取当前被调试函数的局部环境的位置信息							\n"
"function tqdb_capture_vars(savewhat)											\n"
"  local vars = {}																\n"
"  local iupvars = {}															\n"
"  local ilocalvars = {}														\n"
"  local stackframe = tqdb_get_curstackframe()									\n"
"  local func = debug.getinfo(stackframe+4, 'f').func							\n"
"  local i = 1																	\n"
"  while true do																\n"
"    local name, value = debug.getupvalue(func, i)								\n"
"    if not name then break end													\n"
"    vars[name] = value															\n"
"	if savewhat then															\n"
"		iupvars[i] = name														\n"
"	end																			\n"
"    i = i + 1																	\n"
"  end																			\n"
"																				\n"
"  i = 1																		\n"
"  while true do																\n"
"    local name, value = debug.getlocal(stackframe+4, i)						\n"
"    if not name then break end													\n"
"    vars[name] = value															\n"
"	if savewhat then															\n"
"		ilocalvars[i] = name													\n"
"		print('ilocalvars['..i..']='..name)										\n"
"		print(value)															\n"
"	end																			\n"
"    i = i + 1																	\n"
"  end																			\n"
"																				\n"
"  setmetatable(vars, { __index = getfenv(func), __newindex = getfenv(func) })	\n"
"  return vars, iupvars, ilocalvars												\n"
"end																			\n"
"																				\n"
"-- 将当前的被运行修改过环境保存到被调试函数的实际运行环境中					\n"
"--@param vars 修改过后的运行环境												\n"
"--@param iupvars 当前被调试函数的上行函数环境的位置信息						\n"
"--@param ilocalvars 当前被调试函数的局部环境的位置信息							\n"
"function tqdb_save_vars(vars, iupvars, ilocalvars)								\n"
"  local stackframe = tqdb_get_curstackframe()									\n"
"  local func = debug.getinfo(stackframe+4, 'f').func							\n"
"  local i = 1																	\n"
"  while true do																\n"
"	local name = iupvars[i]														\n"
"	if not name then break end													\n"
"	local value = vars[name]													\n"
"	if name ~= '(*temporary)' then												\n"
"		if not value then														\n"
"			debug.setupvalue(func, i, nil)										\n"
"		else																	\n"
"			debug.setupvalue(func, i, value)									\n"
"		end																		\n"
"	end																			\n"
"    i = i + 1																	\n"
"  end																			\n"
"																				\n"
"  i = 1																		\n"
"  while true do																\n"
"	local name = ilocalvars[i]													\n"
"	if not name then break end													\n"
"	print('name='..name)														\n"
"	local value = vars[name]													\n"
"	print(value)																\n"
"	if name ~= '(*temporary)' then												\n"
"		if not value then														\n"
"			debug.setlocal(stackframe+4, i, nil)								\n"
"		else																	\n"
"			debug.setlocal(stackframe+4, i, value)								\n"
"		end																		\n"
"	end																			\n"
"    i = i + 1																	\n"
"  end																			\n"
"end																			\n"
"___db_level___ = 0																\n"
"___db_maxlevel___ = 10															\n"
"--在当前的调试函数环境下执行一个表达式函数体									\n"
"--@param saveval 标示是否需要保存修改过后的运行环境到真正的运行环境			\n"
"function tqdb_exec_expfun(expfun, saveval)										\n"
"  tqdb_exec_retval = nil														\n"
"  local vars, iupvars, ilocalvars = tqdb_capture_vars(saveval)					\n"
"  setfenv(expfun, vars)														\n"
"  local status, res = pcall(expfun)											\n"
"  if status then																\n"
"	tqdb_exec_retval = res														\n"
"	local strtype = type(res)													\n"
"	if strtype == 'table' then													\n"
"		___db_level___ = 0														\n"
"		tqdb_exec_retval = tqdb_print_table(res)								\n"
"	end																			\n"
"																				\n"
"	if saveval then																\n"
"		tqdb_save_vars(vars, iupvars, ilocalvars)								\n"
"	end																			\n"
"																				\n"
"	if type(tqdb_exec_retval) == 'nil' and saveval then							\n"
"		tqdb_exec_retval = 'exec ok!'											\n"
"	end																			\n"
"  end																			\n"
"end																			\n"
"																				\n"
"--将一个table对象显实打印出来													\n"
"--@param tb 将被打印的table													\n"
"--@return																		\n"
"-- 返回打印结果字符串															\n"
"function tqdb_print_table(tb)													\n"
"  ___db_level___ = ___db_level___ + 1											\n"
"  local strret = '{'															\n"
"  for k, v in pairs(tb) do														\n"
"	if type(v) == 'string' then													\n"
"		strret = strret..k..'=\"'..v..'\",'										\n"
"	elseif type(v) == 'function' then											\n"
"		strret = strret..k..'='..'<function>'..','								\n"
"	elseif type(v) == 'function' then											\n"
"		strret = strret..k..'='..'<thread>'..','								\n"
"	elseif type(v) == 'userdata' then											\n"
"		strret = strret..k..'='..'<userdata>'..','								\n"
"	elseif type(v) == 'proto' then												\n"
"		strret = strret..k..'='..'<proto>'..','									\n"
"	elseif type(v) == 'upval' then												\n"
"		strret = strret..k..'='..'<upval>'..','									\n"
"	elseif type(v) == 'nil' then												\n"
"		strret = strret..k..'='..'nil'..','										\n"
"	elseif type(v) == 'boolean' then											\n"
"		if v then																\n"
"			strret = strret..k..'='..'true'..','								\n"
"		else																	\n"
"			strret = strret..k..'='..'false'..','								\n"
"		end																		\n"
"	elseif type(v) == 'table' then												\n"
"		if ___db_level___ < ___db_maxlevel___ then								\n"
"			strret = strret..k..'='..tqdb_print_table(v)..','					\n"
"		else																	\n"
"			strret = strret..k..'=<table...>,'									\n"
"		end																		\n"
"	else																		\n"
"		strret = strret..k..'='..v..','											\n"
"	end																			\n"
"  end																			\n"
"  strret = strret..'}'															\n"
"  ___db_level___ = ___db_level___ - 1											\n"
"  return strret																\n"
"end																			\n"
"																				\n"
"--执行一个表达式，不改变原有的运行环境											\n"
"function tqdb_exec_exp(strexp)													\n"
"  tqdb_exec_expfun(loadstring('return('..strexp..')'), false)					\n"
"end																			\n"
"																				\n"
"--执行一条语句，改变原有的运行环境												\n"
"function tqdb_exec_exec(strexec)												\n"
"  tqdb_exec_expfun(loadstring(strexec), true)									\n"
"end																			\n"
"";

#endif // _DBGLUA_H__
