#----------------------------------------------------------------------
# This file was generated by E:\MyWork\wg\trunk\tool\Src\UIEditorSrc\imgtools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

adddialog = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAXElE"
    "QVQokWP8//8/IyMDAwPDm+cPGYgAjAwM/+EcYvQwEWMqiga4qUQ6iQVZqYikPPWdxILG//8f"
    "qzIoYGTE0AARxWMEFg3IitA049SAqQ6fBvzeGI5+wGM2BAAAvgogBdsxTh4AAAAASUVORK5C"
    "YII=")
getadddialogData = adddialog.GetData
getadddialogImage = adddialog.GetImage
getadddialogBitmap = adddialog.GetBitmap

#----------------------------------------------------------------------
addshape = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAASUlE"
    "QVQokWP8//8/IyMDAwPD6+cPGYgAjAwM/+EcYvQwEWMqiga4qUQ6iYV4pQgNcCAqKU+aBoK2"
    "iUrKk+7pUQ200IAecQQjGwCdABU+yPQpzwAAAABJRU5ErkJggg==")
getaddshapeData = addshape.GetData
getaddshapeImage = addshape.GetImage
getaddshapeBitmap = addshape.GetBitmap

#----------------------------------------------------------------------
bottomalign = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABDklE"
    "QVQokbWSvUoDQRSFvwkWNqIgCgHBgI1gYVqrgBZ27iMIPoVlSksfwSex1i4WQZvALKTwpznB"
    "5prs7ljMMtnYhC28DDOXwzlzzvy4EAJtqtOKDWzE5VufCXp8fgVkSLrJzhK+tbO/dAhVlYaM"
    "7HJwnQ1GT6MmvhKpalRE8o+ZlyKyvdtNeB0pn3wJee+vzi8w+EEmIISal5raQah/3PdvPlSV"
    "0AwwMFKY8McBgSEphIARD80m6dJTUwtkkknvCoAhq/dJb5SazorAVBZzmWQzGRhlMd/r9oA4"
    "Nxyk4e0QKMoFcH/34L2XqSgXUz8+6J1M/TgyXQyXT15YV4dHp0uBc26tIDJb/yX377/1F/GG"
    "y3tVy8QuAAAAAElFTkSuQmCC")
getbottomalignData = bottomalign.GetData
getbottomalignImage = bottomalign.GetImage
getbottomalignBitmap = bottomalign.GetBitmap

#----------------------------------------------------------------------
copy = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAACIklE"
    "QVQokW2RvWsUQRjG39mZ2d2Z3c3dhrskGkEQK8EinZ3YKUEUbCwsrAQFRaKNkEaJoCJoLJSA"
    "op21EiwUO/8PjcTkxL2P3H7c7OzsvDarRrhf/f54Ht6HIOLbdx9RT+rKMioM0rwyX7e+PVy9"
    "CtNgAFBZe255Wfqsn0yitsgN3F17MfUaABwAUGlfCoeCaYWMORD5EM+I66uvrtx+Ml1wKcsn"
    "qjCWSV5MjK3h0sULS8ePHT54aHol14vRlbujQvjuh81PpDaRDLBUoU823rz3fXdnp3dn5fI/"
    "Ienv5Qq2e0MgBZft0ydPxCHRCoSAfloDpU/XX/5XyXGoqWG20+10OlrrMCCcQRiAqTFu0yIr"
    "/KB9697rayv3m4TtH7tK1VmqECBLS2NBIwDAWClBRNyVZ86ez/Piy+fNRiDgCY8yEnBOKQs1"
    "Qp5WIuSaCmMAAETEdOXm2fjPDqUeJTr5OWzH86WGcQ7bvV6aKRFEjDFAWqNf5TkiNkIg3Thy"
    "EWcNQjlRzId4bjGedwgFrRAtoRxSgqosG8GU2fNnj4eZPnJ06fvW1mB06tcwUQapwyutOXPD"
    "KDZ1TSlvhPtrN/9+7cbqhueRAwtzZQ3WAiCYClQJurSUe42wH0r0eJAm48z1pDaWMcf3pQOc"
    "U2atbXbYj3Tp3Ey0ONvFCqGGVquVJINsvBcIropiSkIrctcfPWjF3VRXMppJBiMRSNchDOuF"
    "WALAbypqAjo/f4zNAAAAAElFTkSuQmCC")
getcopyData = copy.GetData
getcopyImage = copy.GetImage
getcopyBitmap = copy.GetBitmap

#----------------------------------------------------------------------
down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAnUlE"
    "QVQokWP8//8/AymAiSTVw0QDCwMDw7uXj9BEw6YJr8p6iyYoJC4H1YA1ZHEFNwsDAwNWGVyx"
    "w8LAwPD3zy9MCayCUA1//v6G8+PnyUuLcjAw/IieLfX87sldrRJoGpgYGBj+/PkNR3Pj7jx9"
    "/UNalOPX+1vbGoWRpSAaGP///3/31hk0YxKnMM/P+YsmqKxmAtWAw3vYAe1jGgAks02twEHY"
    "AwAAAABJRU5ErkJggg==")
getdownData = down.GetData
getdownImage = down.GetImage
getdownBitmap = down.GetBitmap

#----------------------------------------------------------------------
hcenteralign = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABYElE"
    "QVQokZVSPU9bQRA8no7SwlIKSOHKP4JUNFEi0SF+AVLsipR0NARkiXSRUjiIz5SRUluRC6oI"
    "6f2IV1ou6JAs4HZmNsU5zvOrwhR3ezuzN3sfK+4eXoL49WYEkSRIQiQgEQDyiiSB+QAoQuzt"
    "bv7n9vtH1zGE4FI9++3nXUqWzJ6THfa36xTFSFLLBbPZ4877NyGEqx+/GhSA+JyS+1K2jgaV"
    "khWgXHLpw1mRg2S2oBsUyYKku7t7q73eO4/ubosCM3fvncdWez1rSEUC/YvVEEKrHR5sbeug"
    "fNudF5hh66B63d1shZA1JAuQw73ZcG82uX+aVuXtaSelfw63p51pVU7un7KGUgESNNCmVTke"
    "bIBWbwm08WBjWpVZk1siYCGE0adXOVgcGmYNSmLMDkt3Z3by5XsyM6BBSR7JucMCxx/f1V5q"
    "iWJ2+Hz5GxQEgaCYIf2dRJGSyyWtvPR7/wGkv3NXrGh3AQAAAABJRU5ErkJggg==")
gethcenteralignData = hcenteralign.GetData
gethcenteralignImage = hcenteralign.GetImage
gethcenteralignBitmap = hcenteralign.GetBitmap

#----------------------------------------------------------------------
heq = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABJklE"
    "QVQokZWSsUrDUBSGT0PWYLYq2Kkv4CDoEgqC+AIiDoJgdeiiQju7iJihi1NbfAEXERw7FDJJ"
    "3sHMQXCQtkNy7r3nd0iIpkM0PwfuOfB/nP/AbQCgOrJquYnI9sfPAETk6mSvwnc7egUgAvvA"
    "2yKil+kbIBVAmvLp4T4R2fmcMOQPII+UPfPFUiqB+WKZNfnRSZoCAsjZmLJmZUyZSwCzgkh3"
    "YjluEyJFOW6zO7EgwlyOlDJ7/fft3c7i6+P80S6SOC7N1ZrXDzdJlQBmDobtziDYaO889T4L"
    "4HiUxFEYDNtHl2o1ktE881txFBrNRcVROPNbRrNSurxBKW0UEU3v1rMmUzFqUwaISOsfX4V+"
    "AeZ/wPXNAwBAqjdoIxeDeyJq1P3e37yzzt7QY6CDAAAAAElFTkSuQmCC")
getheqData = heq.GetData
getheqImage = heq.GetImage
getheqBitmap = heq.GetBitmap

#----------------------------------------------------------------------
leftalign = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABHklE"
    "QVQokZVSsUoDQRB9JxY2gim0MWCKgME019jY+AmWYhW0s/ITgp1lPsHPSHkgpLGxOUhAdEVB"
    "Y6HvrEZvs2OxUdfLcXCPKWaGmXnvsRupKupgqdY0gGUAURQB+Hif3k2eCYKgkEKSJ4dHfm51"
    "baPIoM4RjDvxL5Jhos75+Mfg4ZwzxiTDhCRfSKFvFiRFquolvb0+VkhvrDeLDOrc1c09BQAg"
    "IAgBBJ6qf9ZbWFAF0DvYB4BPZAAACijZ4OKyxIMC/vzDNKMQMi8pMMaULMzsF8nj03NDelVY"
    "+ZEnLDH9ZNIK05tbOz75ewdrc2vzZqvrk0KUSLKzvL29C6DVjsPbt5PrsAwWbD5OR53u3jgd"
    "hRPh+bmHCumLqP1bvwFeIbFbZprlGAAAAABJRU5ErkJggg==")
getleftalignData = leftalign.GetData
getleftalignImage = leftalign.GetImage
getleftalignBitmap = leftalign.GetBitmap

#----------------------------------------------------------------------
open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABqElE"
    "QVQokZWRv2vTURTFP7FfIYvkQn+gIPIlUtvNaC1GS3HQvSI46OLgn6B/gZN00qmbrZPaKeJg"
    "BxEdigFRv4FChTq84mKFwokIXsg3/Tq8JARpBu9y37v3nPMO55V+/9rnfyopDg5G7b7v7a+/"
    "buJgdmlm8vK5M0BSFCMJy6sbN69dXJyr/vHOyos3Vjm2sv629G3741Zrcxh38tT09Mz5f8jb"
    "O3sP194ByVZrszZrlhpQQTgvN3bGxrppdW6YENFAgmMpAzSwVA9Pm7S+fAZwBLiePLjXJwBO"
    "pdxDowC6U8+G5R83bJBNotgd4H1TYPIagAuQA1iZV89X5YASXDiUbTcEuS3VdUheLqCVhU8/"
    "55PBKAtmFnd9jgPCaUv6oWcfTty+u5Dg4NoVYFdmhaDcc4irHd93rTVVPT0/PjV5JCplwdLj"
    "fXkHF1JbQkIKX0MI1BZu5HknkRMEcDYVUrTb9nhGLkmNYEenLoxPTOTdTgIKIU0ttBqPonMB"
    "bjEfucktBK7eWszzTu8fQsgyB78uRUkkyUW8Ogb3l2t5twOUiqI4JMfR9RdyBe/HdP+Z2wAA"
    "AABJRU5ErkJggg==")
getopenData = open.GetData
getopenImage = open.GetImage
getopenBitmap = open.GetBitmap

#----------------------------------------------------------------------
paste = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAARCAIAAABbzbuTAAAAA3NCSVQICAjb4U/gAAABUUlE"
    "QVQokb2QMUvDQBTH3yVpQpKatINQRFxdLEj9HE4iRdBFEAdXF8eu4qhDEYKtRQc38VtIwcnB"
    "apEirYEUmjRtk0u8OFjvtQWHLr7pd/f+P967I0mSwHSVaxbnw939mS6ZEco1q/7k8uPGujnj"
    "jIXKlUVDlemjyTR32g27VDqZFqq3xeJO5c6CPyoeLR4dbKJwWbve2t5TZEyIBPn84sGxHTZ0"
    "Ts+OpZ8rBlHAwHe/eEgQkdcKhe6n8/5cB4CxYKg6YfDS7OCEiRHZpVxKkxuvjyhAklAK+fwy"
    "D4U4APwASJIOaICC3e6EIby1WriSgN+t6rk4oCQWUfB9P23AamZl4tWIfQ96Uey5PgAIMGfN"
    "Lfx+q0AoA0qxwRhyTCClappp/udKwTD6aHaFlMQbvb7HWZRkRZRoOEBBk4z7m6qsLfBQt9fn"
    "nMmao4FrpBUA+Ab5oYzQDBNZmQAAAABJRU5ErkJggg==")
getpasteData = paste.GetData
getpasteImage = paste.GetImage
getpasteBitmap = paste.GetBitmap

#----------------------------------------------------------------------
redo = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAB1UlE"
    "QVQokZWSTWvUUBSG33xN5qNDglM/MtBUKE4VGRB0paAoiBt3xa3diTsXLsQf4MaN4I8oFiq0"
    "UNfWuhG1gzoUqShMrVo7HeXmziS5SW7udZFOLFgXcziLw+U95znc9yhSSowSOoCB1wsjbO2q"
    "26ES9JUpJ3Vrslg4QD1mjesAgki83igEHN8oAGxRLRrgcpOfdkUuDWOUCkNC67PhRZh76Xnd"
    "toG0bB1y3eZiW1e0+JQjSKTMPvx574Z7/mQEQAVAgYU15cenlfoRbbJe9Tzv1ZsXOz1lvmW0"
    "NtW1TQOMUEAIMWzoizggJS1+cLPx6HZj9qpTQf/dyiL1sPTBXH2vEUZoX0gp9lbK/skZL9fG"
    "DCnEzIXDU8eKT5fXC1WVEBACMCIlZE4wdWkVrUHPl8OYcKzGpWtgIAQdQsCIqcvMAB1AreSH"
    "qt1Nj1I/qlZMALce/wL7QhgBI2CEMNRKvsx9ODcZL7yFffzMx8722ekagCd3yzyt6Fp9nwdx"
    "yrG3Ek+TKye+2rY9v8p5mmQJxHm97zFr4MnFaVH0O7TcfN5OdqnkPDkw/xJ4mtyfYY7Se7Yx"
    "sfOb/zs7J+gZAYBp4M717vr3kCYG58H/jk8Z9VrVkdQA/gAPey/8miWDYwAAAABJRU5ErkJg"
    "gg==")
getredoData = redo.GetData
getredoImage = redo.GetImage
getredoBitmap = redo.GetBitmap

#----------------------------------------------------------------------
rightalign = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABG0lE"
    "QVQokbWSvUoDQRSFv4QNFoqghTYRUgQMpNnGRhAfQbARKzGN+Bh2lj6Cj5FysUgj2EUSUJmA"
    "4l/hCSpM3M2OxcQQkmlSeLjF3Dlzud+dmYJzjnlUnOs0EAGfevPJQ/dZCCErWUlqHBwur6wD"
    "Y5Ai4PLch1Bci8dKmonL80CH/G/XGJM0E0l6kawmrbEKzrmP98cg7tf3YGlxYXVtYxIpAq5u"
    "7mUBsAhhweI7nOzvBJCAo71dgAF9AGSR7V+cXzqmLz3yNtB77csKO0plMcaUSlGoQDo+PTOS"
    "p4IRDzDMfgJDP/Vug0N7lSt1pt4hy9LZKFfqfhFAyoYpUN3cmvIq1fiuex0qyFKg025NGrX6"
    "dqfdmu1Q+Pff+gttS7cU8dRxwQAAAABJRU5ErkJggg==")
getrightalignData = rightalign.GetData
getrightalignImage = rightalign.GetImage
getrightalignBitmap = rightalign.GetBitmap

#----------------------------------------------------------------------
sameattr = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAASklE"
    "QVQokWN88/wBAymABUKJRC4gqPTN8gSEBjgfF4CbyESSe1BsQDbmzfIEZEciW46iAVkClwtH"
    "nUQTJ1HgB2LSHwMDAyOpyRsAmXsqVpjVWLsAAAAASUVORK5CYII=")
getsameattrData = sameattr.GetData
getsameattrImage = sameattr.GetImage
getsameattrBitmap = sameattr.GetBitmap

#----------------------------------------------------------------------
sameh = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABK0lE"
    "QVQokZWRL04DYRDFfzQVCEKaYBEIEgQEh6Y3QKEhAdEgoEfgCHuEHqEHQFABBld6gDUkkAb6"
    "toVkyv5DfOz2220RTCbvGzHz3rz51vI85z/RBL5mHxubW5/Td8AVDu8en3+7jFC6OTsB8BVm"
    "GvvZ79/nRZx3bl3RAKaTN4d5nvmpgiiaE0qLlfIsK3F1WFTxkGXZZPyS/TUwR1Y1PXh4kkmv"
    "knR9deERA0RFsRhot9sYMnW73epiqjzlgOuWVDuaDOaFlHkDQjLJBNR+MaIeTaAX9GQKwxBI"
    "k++aB5lbyTvrZee07EnSeIkUTOWhGkCSxNs7+0kS11JW2X6h4FhXcUuGrGKkAezuHTlcVpBF"
    "GNBqrXsKo+Hg4PB4NBwkaewKh5iCIJCQ5+EHsJ4CPynyMqAAAAAASUVORK5CYII=")
getsamehData = sameh.GetData
getsamehImage = sameh.GetImage
getsamehBitmap = sameh.GetBitmap

#----------------------------------------------------------------------
samesize = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABHklE"
    "QVQokaWRO07DQBCGv7VcAiI4BiTsiMY0PK7AGTgCFUo6unSIS7gMN+ACVDR0aXg0VIiAhJwE"
    "iHGBFLNDsUZarS2ExOrXavb/Z2bnoUSE/5winxb5VB0MjeGoIqKAj/exzS4dPhojP+vY/OJy"
    "KCIeIKJtzAYRMBtEDm/CfEC0rtfWSAIKeBs//6W9VrghIuo1G9nsympsPx21FUaeaB0cZaK1"
    "ATC8ujAwhRkYH8BvdyeAucdp4HYiEvaq4ba7E33e8bI0ALI0yNKgvkL5kYwPoF5G97bHerxl"
    "Px11LUoU8PRw9+t4qhNtbleLK8u5g/j4s06aMB8ov+a1dF4TCdDwQ9L3gKTvNf6gnAS315fA"
    "7snCzWkB7Ozt26qIfANT8uYhDNjT9AAAAABJRU5ErkJggg==")
getsamesizeData = samesize.GetData
getsamesizeImage = samesize.GetImage
getsamesizeBitmap = samesize.GetBitmap

#----------------------------------------------------------------------
samew = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABPklE"
    "QVQokZWSvUoDQRSFv5UtLIMIRvxJiqCgTRpr8wbZxl7BxspHEJ/APEJewdIyTRqbIAaipFhR"
    "MBCFs90NO2EsZlmCICaXYbice+45h2Ei7z2rVHz/0MNQCRggWdmjEjHd3VzHQLt9+ltnRrYg"
    "IUOWdTodIP6TV2iHhQxDAoiDbzYDy2QU8UIYwMqwFZmAOJUurm5TicWywqMwgcp6YRh9T97+"
    "fZmyNrb2I+DrM12Gvbld995H0+XYxU61FgGT99dl2NW9A+999JEOF9HxaCqTTJpI0uX52eJ0"
    "p3a05ly+Wz92Lg8HaLVaSStJkmQwGJR44ABxvdEEwj1+eZSEIZMkwM3zxuFJkK83mt77tdGw"
    "D4yG/dGw71wuSSikApzLwyhwgNjN8+ennpvnQUZSt9OVKU3T4BDwkhOt+r1/AB0l1n1o/3/O"
    "AAAAAElFTkSuQmCC")
getsamewData = samew.GetData
getsamewImage = samew.GetImage
getsamewBitmap = samew.GetBitmap

#----------------------------------------------------------------------
save = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABKUlE"
    "QVQokZWSoXLCQBRFD0xEHPmDVtaBrFxZmU+AL+AXkHVEIpEVFSA60zpUi2vqkJGVd91jKlKx"
    "ywZKEUTsvOzce96+u9tr25ZrvgxYv3kAI6wyMOnPL2DM58Ms7BbFoN4xnSbQIFV+z3jcFAiA"
    "Yb9rZv78AH4P5mXUu1Vw9IHQXaZLaqHyYYYpGoiGC2qFSSIuGNStZ2qZlDI4PdL/6hRUIMaU"
    "MMpyOJl8iag4FJJR3t3KYkxZYAe8c0PJH3gJr7iTDJiwGxmS32xn3eA5RV7IHEeeDFBoEtiw"
    "eqpGzi0XK3KqRaXmJJJuhsQYOefuyyJPHVSAoLAjg8xjWm5rvuvqcQY0TUNOU2+gVLwrAb22"
    "bV/W78+vP5K6qwivLY4XKgk+P+a9a5/3LxvJ9fZPSGl1AAAAAElFTkSuQmCC")
getsaveData = save.GetData
getsaveImage = save.GetImage
getsaveBitmap = save.GetBitmap

#----------------------------------------------------------------------
saveas = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABSElE"
    "QVQokZWSL1NCQRTFfzgEm/sNJNLAbwBN2yPa4BNIY0xANEGz0ijOPAiOmiCpjWczEo1n23UM"
    "z7DLe/4NbNjZ3Tn3nHvO3kqe5+yzqsDywQMYYZeBST+ugDGZNKrh1bmj7JWLi4LoqDj5d7rd"
    "rUMANA5KMfO/G/DvYF5G9roIFQdAUJfpP7RQcjrCFAuIBf+gFZxEulCgcv+FlklFBt9b+htd"
    "BBUYY0oYSdLo9V5EROwOkpHUa7IYUzVwB/pWqyF5GcOBG19uA/3kuhmU22fTQkHYsQzJr59H"
    "6XzaOe+n81qn13eHDuh0FjKwbOchiMgXNrZvGdCsj3AAaZqs7pKvKZUjkM6nwGa1BoYD5w7d"
    "SXvWbs+K9KNpmcc0e86GML6K+Q4HbputN6vFLm0BlTzPb5ePN/cfksqvCNMW7UW0YPM0qew7"
    "3p/qF+/z8VZXSAAAAABJRU5ErkJggg==")
getsaveasData = saveas.GetData
getsaveasImage = saveas.GetImage
getsaveasBitmap = saveas.GetBitmap

#----------------------------------------------------------------------
shapen = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAANklE"
    "QVQokWP8//8/AymAiSTVdNHAwsDA0NjYSKTq+vp6FjiLoGqIuYPQ0/QJVgZSQpZxGKQlAKNk"
    "DaJlZo2DAAAAAElFTkSuQmCC")
getshapenData = shapen.GetData
getshapenImage = shapen.GetImage
getshapenBitmap = shapen.GetBitmap

#----------------------------------------------------------------------
shapes = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAPElE"
    "QVQokWP8//8/AymAiSTVdNHAwsDAwMhIrOr//xlYIKyGBsKqIWoGoadpr4Hx////JAcrSalp"
    "EHoaAH7wDh07LZSTAAAAAElFTkSuQmCC")
getshapesData = shapes.GetData
getshapesImage = shapes.GetImage
getshapesBitmap = shapes.GetBitmap

#----------------------------------------------------------------------
topalign = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABA0lE"
    "QVQokbWSvUoDQRSFv5UU1inSpbcM+AAJGhAsTJ5AX8MypaWP4LNYCYKkVDAwQcSfiJ7trtnZ"
    "HYvZTMg2EsEpZg6X8917mJkshMA2a2crN9CKR5Zlv1pjlr9O+Fo8bwfMZwsh59zJweH13QyQ"
    "Ien0eB9od7qf70/RWUcS6u313L0LVSVjdNQ/G/WnN9NQVe1ONzIbAAJDUrrl+VvupBDCx4sD"
    "4r6OJJNMelUADL6RCUhvlMQmYCr9UiiPmFH6ZTQksQKkyfkE8GWBxRawiy+LaEiiBsbDwXg4"
    "ALwvMGR1AO+Lhmg1Gqzi5TKwuv74cNuckBrEdXlx5ZyTqVEHsn//rT9Hlqrbl2TmdAAAAABJ"
    "RU5ErkJggg==")
gettopalignData = topalign.GetData
gettopalignImage = topalign.GetImage
gettopalignBitmap = topalign.GetBitmap

#----------------------------------------------------------------------
undo = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABsUlE"
    "QVQokZWSTWtTURCG33M/vB9NzIFoS4O1BZFKS8GFqCjtouBORdFVV7r2b/gf3LlW0K0gbkIL"
    "7ioRFKLJ4iTQEktNJ1cT770594yLpO2N4CKzmWFmHt6BdwQzY5pwRul37zDf/X4gGnuWxSIs"
    "8nzAC+dN4AFAoXRuDDCbk+13NbfTs2Y8jhIgEv2zYr9rXV9OgzM5hZfvvYcbsfR455vb6Vn1"
    "Pa43WojVEHZpdm1rvfSp6d66kgCwRgABuy33Y9NuHjg1RfXGZ8S0WClWZu1Bu/pmV0SAMeZU"
    "gYi2ScK34z6rWg3A1r0Lj9fnDqPk6fOf6YCiX4XR2cdADCJICSnFynzy6O7q1UtFNqZccF1/"
    "AQAz2JjcSQRFRATEGMzdKEvJxwGg5MNzxvWpggRRR1UVIcaTqvrw4gGAzlEC4I8lywFx3odX"
    "z1IgBEKgojPh2CuZTgG097uQS9LHtcU00zlAZ8O8cTobF6+3tZRy83JbZ/aE01pPAACOBs6X"
    "lo7CNb+vNpahtZkEsn+BH128/boEUvdvRjoLTvr/VYiG4e2Ljc07yYzv5Kdi2m+1ptoG8BfP"
    "OdT02RC9eQAAAABJRU5ErkJggg==")
getundoData = undo.GetData
getundoImage = undo.GetImage
getundoBitmap = undo.GetBitmap

#----------------------------------------------------------------------
up = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAkklE"
    "QVQokWP8//8/AymAiSTV5GhgYWBg+PTuBZqoT8PzLQ2SaIJ8QhJQG/6hgoRp/xTV9HwanqOJ"
    "I5z0//8/OEqawcArIP709Q82QTXrghvIUhANjP///3/38hGa7WHThFdlvUUTFBKXg/oBa8ji"
    "Cm4WBgYGrDK4YoeFgYHh759fmBJYBRkgfsBhFnZA+5gehBoA935icbu4274AAAAASUVORK5C"
    "YII=")
getupData = up.GetData
getupImage = up.GetImage
getupBitmap = up.GetBitmap

#----------------------------------------------------------------------
vcenteralign = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABg0lE"
    "QVQokZVSPWtUQRQ9u7wmWIqFYCcYkfQWamNhEbFQkChYWggxIJYrqIhso7AxCJLCLgiCWJgi"
    "f0CJq7/AYstllSWdz7yZOeeMxeD6XLXI5RTDPXfux7m3k3PGQawavHxHmaIoSUn69SApSYUh"
    "CYByRerWypm5NLe3Dj+/sfd3+pu9zSpJ2Z651l4dATCeNpcHhyaj4e7GqfYHiV2Rbtmza98K"
    "NxkNP6yf9J9GqkspZ7exvjKZjIbvByfm/Dm7zMDS0os3H5sQQxOaGM4ei3f6n0OIAEKIIcWt"
    "J6sAJFWkirJ1/ePqxXP/lPLuw40SI7IiVRbxvd7/n/YhxhIjqyIpRgB1XT/dfB1CiDGGwJhi"
    "SgkAy4YYAUiuEkklAI/Wlmcpe9uL/Utf2kVKjOyuJDK10dteHE+bC/e+zvnJJKpbKsxwf2dp"
    "PG0AHD1+evnBXpuiknOuSJLpdzPnPwG40t9/21sAFtoUAFud66uPy42Jkk1RtiXJtiU727Jt"
    "AAY6Bz3vn+rGoD5TLV2cAAAAAElFTkSuQmCC")
getvcenteralignData = vcenteralign.GetData
getvcenteralignImage = vcenteralign.GetImage
getvcenteralignBitmap = vcenteralign.GetBitmap

#----------------------------------------------------------------------
veq = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABUUlE"
    "QVQokX1QPUsDQRCdfCBpFE0IiQYUEVJaaWVpGyxthPjRKYL5B55IKm0UCQE16VTsBFH0Hwj+"
    "AAmmEUKUYAQLb+9m9sZiN5e4OTMMy+5782bnTYiZ94+vcovzMDCsw8pNtQgAYQCwhRhcDQDC"
    "cdUlCgA/Qpxd3iOiS4guukhEhESEhCSjkQgAOK6jBCFm/m6/G/1yVvPWGjfAkXhaj+T9jbWS"
    "N52dzVlNA1eyMAAwe35ulGF4NNVoiaGx7ELhpZfqjtT+eDN+Xy4lrrc+DTCemtSmmbl/LYFg"
    "RxBEBJcrgSS3nwgEtYAk+u/VylQmGQMQK6cTzfrTYzFtCMIAQIR+nudfGy2RScbcr9rdXqKX"
    "UoIQM9drz0ab9ZNIdVsa4Ex2Tgt2rDJJIiR1IkkiIqlOr2NJPlwcaA+2bW/ml/7Zio7C7lHX"
    "gy2cwdUAgKg9/AIjePCp0tpOZgAAAABJRU5ErkJggg==")
getveqData = veq.GetData
getveqImage = veq.GetImage
getveqBitmap = veq.GetBitmap

